### ISSUE TITLE
Sort Chinese alphabetically by pinyin

### ISSUE THREAD

**Issue by MasouShizuka** [sxyazi/yazi#1010]
### Please describe the problem you're trying to solve

When `sort_by` is set to `alphabetical` or `natural`, English can be sorted in alphabetical order, but Chinese is not sorted in alphabetical order according to pinyin.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

When `sort_by` is set to `alphabetical` or `natural`, Chinese characters are sorted in alphabetical order of pinyin.

**Comment by sxyazi** [comment]
Each Chinese character is inherently unordered, it's hard to say whether "中" (zhong) or "文" (wen) should come first, if we sort them by Pinyin, "文" (wen) comes before "中" (zhong) since `w < z`, but that doesn't make sense. 

Also, Chinese (all CJK languages) is a complex linguistic system, I don't think there's an efficient way to sort them, nor have I seen any file manager that supports Chinese sorting.

If you really need it, I plan to open up the file list interface to users, allowing them to load file lists from external sources (such as `fd` or `rg` or any of your script output). You can implement it as a plugin then. Closing as not in the plan.
