### ISSUE TITLE
Flavor specification changes

### ISSUE THREAD

**Issue by uncenter** [sxyazi/yazi#1076]
### Please describe the problem you're trying to solve

I'd like to move discussion from https://github.com/catppuccin/yazi/pull/2 to here. To summarize, I don't see why Yazi needs to mandate the filenames and presence of files not directly related to Yazi. I understand if the spec requires the syntax highlighting and theme.toml files to exist with certain names, but the rest (README, preview image, licensing) does not need to be mandated.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Remove the requirement of the `README.md`, `LICENSE`, `LICENSE-tmtheme`, and `preview.png` files.

**Comment by sxyazi** [comment]
Hi, they are files reserved for future plans, they are added to the specification to avoid using different names for files with the same purpose, e.g. a preview image may have different combinations of `preview.png`, `screenshot.png`, `image.png`, etc., which would make it more difficult to deal with them.

It's probably best to have a file that specifies the name of the preview file, something like:

```
# package.json
{
  "preview_file_name": "preview.png"
}
```

But I want to avoid it as much as possible, which introduces unnecessary complexity.

On the other hand, this also specifies that the image format used is PNG and not other JPG, WebP, HEIC, JPEG XL, etc. This is to make sure that all users get the same experience, because PNG is a pretty mature format and almost all devices support it, whereas with other such as WebP [some devices may not be able to preview them](https://github.com/catppuccin/yazi/pull/2#issuecomment-2002530247), which would be an inconvenience. 

Closing as not in the plan, sorry.

**Comment by uncenter** [comment]
I'll give this one last shot!

> whereas with other such as WebP https://github.com/catppuccin/yazi/pull/2#issuecomment-2002530247,

Yazi itself supports WebP preview images though? That should be the only support considered imo.

> files reserved for future plans

Any chance you can shed some light on what these future plans are? Would help to understand the reasoning behind the spec.
