### ISSUE TITLE
Feat: Yazi shell can support auto suggestions like zsh or nvim cmp

### ISSUE THREAD

**Issue by chaozwn** [sxyazi/yazi#1080]
### Please describe the problem you're trying to solve

Now using the shell in yazi has some hints that there is no history, resulting in particularly long command typing that is cumbersome. Can I have the pale color show previously entered commands and completions.

### Would you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

Just make a request

**Comment by sxyazi** [comment]
Nice to have! Please raise a PR for it.

**Comment by sxyazi** [comment]
@chaozwn would you still like to give this a go? All good if you don't, just let me know!

I want to close this issue because it has been inactive for a while and is a duplicate of https://github.com/sxyazi/yazi/issues/51. Generally, I close duplicate issues unless there's new content to discuss or someone wants to grab it up.
