### ISSUE TITLE
Preview images in the Sixel support fork of `st` terminal

### ISSUE THREAD

**Issue by lennartack** [sxyazi/yazi#1093]
### Please describe the problem you're trying to solve

I'm using st with the Sixel patch. Image previews are only working if I set `export TERM_PROGRAM=BlackBox`.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

It would be nice if there is a configuration option to set the image preview method explicitly.

**Comment by sxyazi** [comment]
I don't think it's necessary because Yazi already supports detecting whether a terminal supports Sixel through the [DA1 sequence](https://vt100.net/docs/vt510-rm/DA1.html) - the terminal needs to respond with the correct value to indicate Sixel support. 

Unfortunately, it seems that several popular forks of `st` with Sixel support don't handle it correctly. If you're using https://github.com/galatolofederico/st-sixel, please apply this patch to the [`config.h` file](https://github.com/galatolofederico/st-sixel/blob/808320d2b18d559c1a162428d40ec4af842b461a/config.h#L24-L25):

```diff
/* identification sequence returned in DA and DECID */
- char *vtiden = "\033[?6c";
+ char *vtiden = "\033[?4;6c";
```

Then recompile `st` and run `echo '\033[c'; cat` in the terminal, you should see the following output:

```
^[[?4;6c
```

This way, other Sixel-compatible CLI/TUI tools will also benefit.

**Comment by lennartack** [comment]
> ```diff
> /* identification sequence returned in DA and DECID */
> - char *vtiden = "\033[?6c";
> + char *vtiden = "\033[?4;6c";
> ```

That works! I'm using st-flexipatch, which does say it uses a Sixel DA sequence, but a slightly different one: https://github.com/bakkeby/st-flexipatch/blob/aa5957495d315a2aca2a846a48ba9f7557353ec5/config.def.h#L57

**Comment by sxyazi** [comment]
Please try https://github.com/sxyazi/yazi/pull/1094 without the patch, this PR should fix this problem.

**Comment by lennartack** [comment]
> Please try #1094 without the patch, this PR should fix this problem.

#1094 fixes it.

> Then recompile `st` and run `echo '\033[c'; cat` in the terminal

In case someone finds this, I think it should be `echo -e` for most versions of echo.
