### ISSUE TITLE
Improving discoverability

### ISSUE THREAD

**Issue by tesujimath** [sxyazi/yazi#1098]
### Please describe the problem you're trying to solve

I am an early-days user of Yazi, loving it so far, but struggling to internalize the keybindings.  I wonder if we could improve discoverability here?

For example, Magit (probably the Gold standard in discoverability) allows you to hit `?` at any time, and [pops up a window](https://emacsair.me/2017/09/01/magit-walk-through/#the-popup-of-popups) showing available keybindings and their commands.  This is context sensitive, so reflects what mode you may be in.  This greatly improves the onboarding experience, and is a boon even for experienced users doing something unfamiliar.

Would something similar be appropriate for Yazi?  Or perhaps there's already something I'm unaware of?!

### Would you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

A global and context sensitive help key (e.g. `?` or `C-h`) which pops up keybindings and their descriptions for the current mode.

It would have to be hierarchical, so e.g. `c` would be shown for copy, and when selected, hitting the help key again would pop up the subcommands for copy.

**Comment by sxyazi** [comment]
Hey, Yazi has a `~` key that sounds like the feature you're describing. 

It opens a context-sensitive help menu (specific to components rather than modes) - you can use it on different components: for example, pressing `~` in the input component brings up the list of available keys for the input, while pressing it in the manager component shows the keys available for the manager, and so on.

BTW the choice of `~` instead of `?` is because `?` is used for upward finding.

**Comment by tesujimath** [comment]
Oh wow, I see that now. Sorry I overlooked it. It's almost the first thing on the quick start!

Thanks for making Yazi. It's awesome! 👍😅
