### ISSUE TITLE
command prompt

### ISSUE THREAD

**Issue by Joao-Queiroga** [sxyazi/yazi#1153]
### Please describe the problem you're trying to solve

I don't want to necessarily put every command I want to use to a keybinding

### Would you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

An input to commands just like there is to shell commands, but to yazi commands

### Additional context

It would be good to have the ability to type a yazi command that is not used often instead of having to assign every command to a keybinding.

**Comment by sxyazi** [comment]
You can implement it through the plugin system, which essentially is just a combination of two APIs: [`ya.input()`](https://yazi-rs.github.io/docs/plugins/utils#ya.input) and [`ya.manager_emit()`](https://yazi-rs.github.io/docs/plugins/utils#ya.manager_emit) - you can call `ya.input()` to accept user input commands, then call `ya.manager_emit()` to emit these commands.

Closing as it can be implemented through a plugin, and there are no plans to offer it as a built-in feature since I found it is rarely used.

**Comment by sxyazi** [comment]
Check out https://github.com/KKV9/command.yazi
