### ISSUE TITLE
Plugins installed by `ya pack` shouldn't go into config directory.

### ISSUE THREAD

**Issue by SolitudeSF** [sxyazi/yazi#1157]
### Please describe the problem you're trying to solve

Config directory should have user configuration intended for user modification. Placing user plugins and installed plugins into the same directory leads to confusion, risk of modifing plugins that will be overwritten on the update anyway, complicating dotfile management and polluting file-tree with `DO_NOT_MODIFY_ANYTHING_IN_THIS_DIRECTORY` noise.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Yazi should load plugins from `XDG_DATA_HOME` (`.local/share/`) or appropriate alternative.

**Comment by sxyazi** [comment]
What should be done if a plugin with the same name exists in both `.local/share/` and `~/.config/plugins`?

**Comment by SolitudeSF** [comment]
i would imagine an explicit user configuration should always take the priority.

**Comment by sxyazi** [comment]
Do you mean a config option determines which location to check first, or does it mean it only uses which one location?

**Comment by SolitudeSF** [comment]
i mean that plugins in `.config` should take precedence over `.local/share`

**Comment by sxyazi** [comment]
I think this will cause confusion as some plugins come from `.local/share/`, while others come from `.config`, which will reduce observability - users will need to pay attention to the contents of both directories at the same time. And we have to introduce a priority for it.

Also this will add unnecessary complexity - we will have to explain the differences and purposes of these two directories in the documentation. It will also be inconvenient for users when they install plugins from the web and review their code, as they will have to find them in `.local/share/` instead of the more familiar `.config`.
