### ISSUE TITLE
Update windows installation instructions

### ISSUE THREAD

**Issue by ShrykeWindgrace** [sxyazi/yazi#116]
Both `unar` and `poppler` are available in `scoop` - since the recommendation to install `yazi` points to `scoop`, we might as well install other stuff via the same tool.

I do not have file preview at all (#115), so I can not confirm that these scoop-installed tools work well with scoop-installed `yazi`.

**Comment by sxyazi** [comment]
Great idea, I'll test tomorrow to see which ones can be installed from Scoop.

**Comment by sxyazi** [comment]
Hi, I have changed the Windows installation guide to use Scoop and included `unar` and `poppler`.

But still keep using the `file(1)` command from Git as the recommended method, since I have found that Scoop's `file(1)` does not handle Unicode file names well, such as `pexels-oliver-sjöström-1433052.jpg`.

https://github.com/sxyazi/yazi/wiki/Windows-Installation-Guide
