### ISSUE TITLE
Match the file name with path while using filter/find in the search result panel

### ISSUE THREAD

**Issue by QiBaobin** [sxyazi/yazi#1166]
### Please describe the problem you're trying to solve

Like, search the files with same/similar name in the current path using fd, then try to filter/find in the result, it's hard as they are have same name, I have to navigate manually.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

I think it makes more sense to match the file name with sub path instead of only the file name.

**Comment by sxyazi** [comment]
You can specify the `-p` parameter for `fd` to accurately search files by their path rather than just the filename, instead of relying on fuzzy searching by filename and then filtering them:

```bash
# The latest main branch is required at the time
{ on = [ "f" ], run = 'search fd --args="-p"' }
```


Just `fd 'init.lua'`:

![screenshot-000623](https://github.com/sxyazi/yazi/assets/17523360/db9faad5-dec9-49a4-9916-776bf2adcae4)


`fd -p 'arrow.+/init.lua'` (You can use any regular expression):

![screenshot-000624](https://github.com/sxyazi/yazi/assets/17523360/e6f6422e-02be-4df9-8f35-d438d3d96165)

If you prefer glob over regular expressions, add the `-g` parameter. Refer to the fd documentation for details.

**Comment by QiBaobin** [comment]
@sxyazi , thanks for the quick reply. I think I didn't make it clear.

 I knew I could search with path, I meant I couldn't use `f` or `/` to navigate or narrow down after the searching, I want keep the search result.
