### ISSUE TITLE
Add manpages.

### ISSUE THREAD

**Issue by voronind-com** [sxyazi/yazi#1196]
### Please describe the problem you're trying to solve

They can only have a link to documentation if proper manpages are too much. It is unpractical to open a web wiki for all the stuff we use. And the scope of this tool is too small to have a dedicated web wiki.

### Would you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

Proper manpages or just a link to wiki so that new users won't get lost.

**Comment by sxyazi** [comment]
I don't have enough time to maintain another manpage besides the current web document. I've tried using `pandoc` to convert the web document into a manpage, but the result was not satisfactory because they are not specifically formatted for a manpage and a lot of information (anchors, images, videos) would be lost. 

However, I don't mind accepting a PR that simply adds a link as a manpage, so that at least users can more easily find the documentation URL for Yazi. 

Closing as not in the plan.
