### ISSUE TITLE
Alias shell support

### ISSUE THREAD

**Issue by AnirudhG07** [sxyazi/yazi#1206]
### Please describe the problem you're trying to solve

I have a ton of aliases, like for example instead of lazygit, I am used to typing `lg`. So when I press `:` for shell, and type lazygit, it works fine but not with `lg`.
Similarly for other aliases too. 

### Would you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

If from my ~/.zshrc (or bashrc, etc.) aliases can be ran through a flag `--alias` then it would be great. This would add on the functionalities.

### Additional context

Also I don't know how to write lua/rust but if someone can help me with how to do it. I am willing to work on this.

**Comment by sxyazi** [comment]
Yazi uses `sh` by default because it's available on all platforms, on most Linux systems, `sh` points to `bash`, so if your aliases are defined in `bashrc`, it should work fine.

For `zsh`, a potential solution is to allow users to set the default shell, but this would require us to adapt to different shells (`zsh`, `fish`, `nushell`), which would be a complex task due to needing to consider the [specific behaviors](https://github.com/sxyazi/yazi/pull/742#issuecomment-1972465004) and all edge cases of each shell. I don't have plan to support this, but I'm open to reviewing and accepting PRs for it.

Another solution is to define those aliases in Yazi, like:

```sh
{ on = [ ":", "l", "g" ], run = "shell lazygit --block --confirm" }
```

Or, if you just want to use `zsh`, you can achieve it with a simple plugin (save it as `~/.config/yazi/plugins/zsh.yazi/init.lua`):

```lua
return {
  entry = function()
    local value, event = ya.input {
      title = "Zsh shell:",
      position = { "top-center", y = 3, w = 40 },
    }
    if event == 1 then
      ya.manager_emit("shell", {
        "zsh -c " .. ya.quote(value, true),
        block = true,
        confirm = true,
      })
    end
  end,
}
```

Then bind it in your `keymap.toml`:

```sh
{ on = [ ":" ], run = "plugin zsh" }
```

**Comment by AnirudhG07** [comment]
That did not work.
<img width="1046" alt="image" src="https://github.com/sxyazi/yazi/assets/146579014/a72e045a-fd5f-4462-aeec-50e8537623e2">

This is how it looks like. I tried changing the keymap directly where it originally as well as adding separately like-
```
[[manager.prepend_keymap]]
on = [":"]
run = "plugin zsh"
desc = "Run zsh commands"
```
Although if I do `plugin --sync zsh`, it didnt show the error. but didnt work either.

**Comment by sxyazi** [comment]
I've updated the code, try it again. This is how it works on my side:


https://github.com/sxyazi/yazi/assets/17523360/6eeac180-0364-436b-ba6c-02e8d4127a3e

**Comment by AnirudhG07** [comment]
I donno why it is not working for me :( . Is their any thing I can send details on so that it can be debugged? It looks ideal at your end.

**Comment by sxyazi** [comment]
This plugin essentially does: 

```sh
sh -c 'zsh -ic "your-alias-here; exit"'
```

so you can run it directly in your shell and see what happens.

**Comment by AnirudhG07** [comment]
That worked perfectly. it opened lazygit nicely.

oh wait. I see what might be the problem. I have setup few commands to run when my zsh opens like taskwarrior. Thats why it didnt open directly. Although lazygit takes over the whole screen so it should technically work in yazi as well. What do you think? ( This is a bit personal customisation going on here)

Ill report back to you the results after I remove them.

**Comment by AnirudhG07** [comment]
It works fine even with and without having the extra text and commands.
