### ISSUE TITLE
Turn off the built-in syntax highlighting feature?

### ISSUE THREAD

**Issue by aidancz** [sxyazi/yazi#1256]
### Please describe the problem you're trying to solve

I want the preview to be in black and white only

But there doesn't seem to be an option to control this behavior

I'm trying to use a simple .tmTheme file to override the colors, but it seems like I can only use #rrggbb and not the 16 colors of the terminal

Also, there seems to be no option to control the cursor shape. I want to use a block cursor instead of a bar cursor even in insert mode.

### Would you be willing to contribute this feature?

- [x] Yes, I'll give it a shot

### Describe the solution you'd like

add option that turns off syntax highlighting

add option that controls cursor shape

### Additional context

`theme_preview.tmTheme`

```
<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
<dict>
	<key>name</key>
	<string></string>
	<key>settings</key>
	<array>
		<dict>
			<key>settings</key>
			<dict>
				<key>background</key>
				<string></string>
				<key>foreground</key>
				<string>#616161</string>
			</dict>
		</dict>
	</array>
	<key>uuid</key>
	<string></string>
</dict>
</plist>
```

_No response_

**Comment by sxyazi** [comment]
Why do you want to disable highlighting? In what situations would you need to do this? If you're worried about speed, Yazi's code highlighting is almost as fast as plain text preview, so this shouldn't be a factor to consider.

If you really don't want it, you can easily achieve this by customizing the previewer. You can refer to the code in [`file.lua`](https://github.com/sxyazi/yazi/blob/main/yazi-plugin/preset/plugins/file.lua), just replace the `file` command with `cat`, or use Lua's built-in `io.open()` to read files for cross-platform compatibility.

See the previewer doc at: https://yazi-rs.github.io/docs/plugins/overview#previewer and https://yazi-rs.github.io/docs/configuration/yazi#plugin.previewers

> Also, there seems to be no option to control the cursor shape

This is by design; disabling it isn't supported because the cursor shape indicates the current mode (normal mode/insert mode). Without it, I'm not sure how users would know which mode they are in.

**Comment by aidancz** [comment]
Thank you for your quick and patient response!
I simply don't like too many colors, too many colors can be overwhelming.

As for the cursor shape, since I don't use normal mode, I don't need to distinguish between the two.

Thank you for creating such a great software!
I am migrating from lf and feel that yazi is more stable and fast👍
