### ISSUE TITLE
Yazi does not boot in Prompt

### ISSUE THREAD

**Issue by tommasongr** [sxyazi/yazi#1280]
### What system are you running Yazi on?

macOS

### What terminal are you running Yazi in?

Prompt 3.0.4

### `yazi --debug` output

<details>

```sh
Yazi
    Version: 0.2.5 (Homebrew 2024-04-23)
    OS: macos-aarch64 (unix)
    Debug: false

Emulator
    Emulator.via_env: ("xterm-256color", "")
    Emulator.via_csi: Err(deadline has elapsed)
    Emulator.detect: Unknown([])

Adaptor
    Adaptor.matches: Chafa

Desktop
    XDG_SESSION_TYPE: None
    WAYLAND_DISPLAY: None
    DISPLAY: None

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL: Some("/bin/zsh")
    EDITOR: Some("nvim")
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE: None
    YAZI_CONFIG_HOME: None

file(1)
    Version: Ok(Output { status: ExitStatus(unix_wait_status(0)), stdout: "file-5.41\nmagic file from /usr/share/file/magic\n", stderr: "" })

Text Opener
    default: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

tmux
    TMUX: false

Ueberzug++
    Version: Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/Users/tommaso/.local/state/yazi" directory.
```

</details>

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

Yazi does not boot correctly in [Prompt](https://panic.com/prompt/) terminal, similar to #844.

This is the sequence shown: `Gi=31,s=1,v=1,a=q,t=d,f=24;AAAA`

Here a recording of the bug:

https://github.com/sxyazi/yazi/assets/25225746/53034981-8692-4231-b02b-18f28564fa2e

### Expected Behavior

Yazi should run instantly without showing the sequence.

### To Reproduce

Run `yazi` in Prompt terminal.

**Comment by sxyazi** [comment]
Unfortunately, I installed and tested `Prompt`, but it doesn't provide any values that can identify the terminal type (`$TERM`, `$TERM_PROGRAM`, `$__CFBundleIdentifier`), nor does it have any terminal-specific environment variables available, such as Kitty's `$KITTY_WINDOW_ID`, iTerm2's `$ITERM_SESSION_ID`, or WezTerm's `$WEZTERM_EXECUTABLE`, etc. It also doesn't support the escape sequences used for **detecting** ([DA1](https://vt100.net/docs/vt510-rm/DA1.html)) [Kitty's graphics protocol](https://sw.kovidgoyal.net/kitty/graphics-protocol/#querying-support-and-available-transmission-mediums) or [keyboard extension protocol](https://sw.kovidgoyal.net/kitty/keyboard-protocol/#detection-of-support-for-this-protocol).

This issue isn't related to https://github.com/sxyazi/yazi/issues/844 you mentioned, because Windows' `cmd.exe` supports Kitty's graphics protocol and keyboard extension protocol **detection** sequences ([DA1](https://vt100.net/docs/vt510-rm/DA1.html)). The only problem is that ConPTY distorts these sequences a bit, so I can bypass ConPTY's limitations by adjusting the sequences and passing them to `cmd.exe` as is. However, `Prompt` is different since it doesn't support them at all.

In this case, Yazi can't do anything about it. You need to switch to a more modern terminal emulator or request that the `Prompt` developers add support for these features.

**Comment by tommasongr** [comment]
HI there, thanks for the time you took for testing the issue.

I'm not sure why you don't see the `$TERM` env... If I echo that on my machines I see `xterm-256color`.
Since Prompt is distributed through the App Store you have to install an [additional component](https://help.panic.com/prompt/prompt-local-terminal/) to use it correctly on a local machine without sandbox limitations. Did you installed that too? Maybe that's why you don't see the variable 🤷‍♂️

Anyway, if you confirm me that the issue can't be solved on your side, I'll reach out to the developers and ask if they can do something. After all the terminal is pretty new, just a few months old. I'm sure they want to support all the modern features.

**Comment by tommasongr** [comment]
Thanks once again! I really appreciate the time you're giving to this. I'm sorry if I didn't get you right the first time. On the topic I'm a mere user, not really aware of the inner workings.

Anyway I'll send this issue to the devs and wait for a fix on their side.

Thanks!
