### ISSUE TITLE
Yazi having issues with mtime and ctime sorting

### ISSUE THREAD

**Issue by PoisonFrog** [sxyazi/yazi#1282]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

kitty

### `yazi --debug` output

Yazi
    Version: 0.2.5 (Arch Linux 2024-04-27)
    OS: linux-x86_64 (unix)
    Debug: false

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect: Kitty

Adaptor
    Adaptor.matches: Kitty

Desktop
    XDG_SESSION_TYPE: Some("x11")
    WAYLAND_DISPLAY: None
    DISPLAY: Some(":0.0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL: Some("/usr/bin/zsh")
    EDITOR: Some("nvim")
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE: None
    YAZI_CONFIG_HOME: None

file(1)
    Version: Ok(Output { status: ExitStatus(unix_wait_status(0)), stdout: "file-5.45\nmagic file from /usr/share/file/misc/magic\nseccomp support included\n", stderr: "" })

Text Opener
    default: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

tmux
    TMUX: false

Ueberzug++
    Version: Ok(Output { status: ExitStatus(unix_wait_status(0)), stdout: "ueberzugpp 2.9.6\n", stderr: "" })

### Did you try the latest nightly build to see if the problem got fixed?

No, and I'll explain why below

### Describe the bug

When setting the sorting by creation and modification time I noticed that this is extremely inaccurate in Yazi. Many files I download from the internet are lacking a **Create Date** and **Modify Date** in their exif data and I believe Yazi uses that for sorting.

![image](https://github.com/sxyazi/yazi/assets/74987652/feb73949-b9cf-49b7-8127-0372afc69d80)

I also noticed that Thunar File Manager and ranger use the "File Inode Change Date/Time" and "File Modification Date/Time" for creation date and modification date and their sorting is WAY more accurate than Yazi's. Same file exif data in Thunar:
![image](https://github.com/sxyazi/yazi/assets/74987652/93c37f60-15d2-4f57-a1f5-68b9255fa97b)

exiftool output from the same file:
![image](https://github.com/sxyazi/yazi/assets/74987652/7200ab0e-e481-4dd2-96c3-f2cc1793e818)

### Expected Behavior

Files being sorted in the order they were created or modified in my machine

### To Reproduce

Download a bunch of files from the Internet (I have around  150 in my Downloads folder right now) and sort by mtime or ctime. The sorting of many files will not make sense, but other file managers handle that very well.

**Comment by sxyazi** [comment]
About the issue with `ctime` sorting, that's expected behavior. Due to a bug in the Rust programming language itself, Yazi doesn't support it in the latest release. 

![screenshot-001624](https://github.com/sxyazi/yazi/assets/17523360/2599cd54-cd89-4d9f-88b8-12f38ba3f48b)

See https://yazi-rs.github.io/docs/configuration/yazi#manager.sort_by

But since Rust officially fixed it recently, Yazi nightly now supports it, you can either build it from the source or wait for the next release for now.

---

As for the `mtime` sorting? I just tested it and didn't find any problems, can you confirm and provide the reproduction steps?

---

As for the output from `exiftool`, it's an independent program and has nothing to do with Yazi. Yazi also doesn't use `exiftool` for its timings. If you encounter issues with `exiftool`, please report them to its developers.

**Comment by PoisonFrog** [comment]
> As for the `mtime` sorting, I just tested it and didn't find any problems, can you confirm and provide the reproduction steps?

I have been looking more into it since I created this issue and I realized that mtime is working as it should after all. It is just ctime that is not working properly. I'm closing the issue since this is a rust bug that was already fixed.
