### ISSUE TITLE
Next Tab macros?

### ISSUE THREAD

**Issue by gotbletu** [sxyazi/yazi#1318]
### Please describe the problem you're trying to solve

is there a way to execute a command and get the next tab path using a variable?

this is possible in ranger, theres a thing called macros so im not sure if it exist on yazi yet

>        Macros can be used in commands to abbreviate things.
>         %f   the highlighted file
>         %d   the path of the current directory
>         %s   the selected files in the current directory
>         %t   all tagged files in the current directory
>         %c   the full paths of the currently copied/cut files
>         %p   the full paths of selected files
> 
>        The  macros  %f, %d, %p, and %s also have upper case variants,
>        %F, %D, %P, and %S, which refer to the next tab. 
>        To refer to specific tabs, add a number in between.  (%7s = selection of the seventh tab.)

This was some of the ranger commands/binding i was using for example
```
map rX   shell atool -e -X %D %s
map cp   shell cp -n -- %s %D
map mv   shell mv -n -- %s %D
map ry  shell rsync --update -r %s %D
```

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

add some of those ranger macros ideas so we all can use it in our custom shell commands keybindings.

e.g i want to extract a zip file (current tab) into the next tab using just a keybinding.

or any other commands really like rsync, cp, mv ...etc

**Comment by sxyazi** [comment]
In the current tab, Yazi has a set of equivalents like `$0` for `%c`, `$PWD` for `%d`, `$@` and `$*` for `%p`. For `%f` and `%s`, you can get them using `basename`, like `$(basename "$0")`. I'm not sure what `%t` means in the context of "tagged files"

As for referencing paths across tabs, it’s not directly supported right now, but you can achieve it through the plugin system. In your plugin, you can access file data from all tabs via `cx.tabs`. You might have something like this:

```lua
-- ~/.config/yazi/plugins/my-shell.yazi/init.lua
local function quote(tab)
  return tab and ya.quote(tostring(tab.current.hovered.url)) or ""
end
return {
  entry = function(_, args)
    ya.manager_emit("shell", {
      block = true,
      confirm = true,
      args[1] .. " " .. quote(cx.tabs[1]) .. " " .. quote(cx.tabs[2]),
    })
  end,
}
```

And the keybindings:

```sh
{ on = "D", run = 'plugin my-shell --sync --args=diff', desc = "Diff tab1 and tab2" },
{ on = "E", run = 'plugin my-shell --sync --args=echo', desc = "Echo tab1 and tab2" },
```

Yazi now uses the native `$` syntax from the shell and relies on the shell to expand them instead of implementing its own interpreter and I also want to avoid introducing a different `%` syntax. 

If we were to support it directly, we'd need to figure out a way to make both compatible.

**Comment by gotbletu** [comment]
Thanks for the reply, hopefully there is a better solution in the future.

**Comment by sxyazi** [comment]
Tracked by https://github.com/sxyazi/yazi/issues/51
