### ISSUE TITLE
Piping data from the built-in prompt into a script

### ISSUE THREAD

**Issue by wojciech-kulik** [sxyazi/yazi#1344]
### Please describe the problem you're trying to solve

I don't like that I have to show the terminal if my simple script binding requires an input. I know it could be worked around using `lua` plugin, but for simple scripts I would like to stay with TOML config.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

It would be nice to show a simple input UI already built-in to gather some text and pass it to the next command. I would like to have something like:

```
{ on = "a", run = [ "show-input", "shell --block --confirm 'echo "$INPUT_DATA"'" ] }
```

or something like that

**Comment by sxyazi** [comment]
I don't think this makes sense because Yazi's commands are executed concurrently. The `show-input` command needs to wait for user input, so it's an asynchronous command. This means the `shell` command will execute immediately without waiting for `show-input`.

Also, while `show-input` is running, any background plugin could interrupt it (plugins have full control over the input component), leading to incorrect shell parameters unless we introduce additional execution state between commands.

In Yazi, plugins are first-class citizens. The functionality you're describing can easily be implemented through the plugin system and would make a great general-use plugin. What you're asking for is very similar to https://github.com/Ape/open-with-cmd.yazi.

Given these reasons I'm going to close this issue as it's not in the plan.

**Comment by wojciech-kulik** [comment]
I tried to create such a plugin, but with the current syntax of `args` it looks pretty messy. Imagine something like that:

```
run = "plugin --async run-with-input --args='--block --confirm --title=\"Archive name:\" --command=\"zip %s $@\"'"
```

and it is just for a simple case. That's why it would be better to have it built-in. As you said, the current implementation wouldn't work because of asynchronous issues. So maybe, there could be introduced a different mechanism for such case?

Like:
```
run_with_input = "shell --block --confirm 'zip %s.zip $@'" , input_title = "Archive:" 
```

However, I understand if you don't want to introduce more options in the config and if you prefer to delegate such cases to Lua.

**Comment by sxyazi** [comment]
I plan to simplify the `shell` and `plugin` commands in the next target (0.3.1) by adding macros. At that point, you'll be able to write it as:

```shell
!run-with-input "zip %s $@" --block --title="Archive name:"
```

where `!run-with-input` represents `plugin run-with-input --args='...'` (note that the `plugin` command doesn't have the `--async` flag because it's asynchronous by default). 

The `--confirm` option will also be deprecated in the next target, as it will no longer be necessary once we require the explicit `--interactive` option.

Similarly, `shell` commands will also be simplified. For example, `shell --block --confirm 'echo "$@"'` can be written as `:echo "$@"`.

I believe that through this series of simplifications, it will allow plugins to be more expressive.

**Comment by wojciech-kulik** [comment]
Sounds great! Those changes will simplify keymaps a lot.
