### ISSUE TITLE
Support Emacs' eat

### ISSUE THREAD

**Issue by arthsmn** [sxyazi/yazi#1345]
### Please describe the problem you're trying to solve

I would like to add support for the new Emacs terminal eat (emulate a terminal). It supports sixel.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Add it to the list of terminals in the code.

### Additional context

Link to the repository: https://codeberg.org/akib/emacs-eat/

**Comment by sxyazi** [comment]
Hi, I haven't used Emacs' eat myself, but Yazi checks the terminal's Sixel support status [through DA1](https://vt100.net/docs/vt510-rm/DA1.html). 

If Emacs' eat supports it and returns the correct response sequence, it should work out of the box without any extra setup. Is it not working for you? If not, have you tried the latest code? I recently [fixed a bug](https://github.com/sxyazi/yazi/pull/1094) with Sixel detection, so that might be related.

**Comment by arthsmn** [comment]
> Hi, I haven't used Emacs' eat myself, but Yazi checks the terminal's Sixel support status [through DA1](https://vt100.net/docs/vt510-rm/DA1.html).
> 
> If Emacs' eat supports it and returns the correct response sequence, it should work out of the box without any extra setup. Is it not working for you? If not, have you tried the latest code? I recently [fixed a bug](https://github.com/sxyazi/yazi/pull/1094) with Sixel detection, so that might be related.

Thanks for the quick response! Indeed, with the latest version the detection works as expected. Sorry to bother!
