### ISSUE TITLE
Even More VimMode Feature

### ISSUE THREAD

**Issue by garcialn** [sxyazi/yazi#1354]
### Please describe the problem you're trying to solve

Recently i found myself in a situation where i wanted to change the name of several files inside a folder, a situation where [oil.nvim](https://github.com/stevearc/oil.nvim) is amazing at... 
![image](https://github.com/user-attachments/assets/b7cf7348-bc5a-4192-9754-47f3262eaf5a)
Yazi is already the best file manager (in my opinion at least), and i know there are already several Vim Motions implemented to the standard use. That said, i still think it would be nicer if i could use it almost like oil is used, opening more possibilities to the user.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

To get closer (and better) than oil, `h, j, k, l` would be used to move the cursor, `<enter>, <bs>` to enter and exit folder, to add a new file/folder(s), you can just add as many lines as you need with 2 keys (number of lines and `o`) and type the name(s), to delete file/folder(s) you just delete the lines you want, to change the name of several files (to add a prefix, as it was my case) you can just `C-v` -> `M-i` and change the lines... It would be important also to keep a key for selecting files/folders, this is something i also would love with nvim itself...

**Comment by wojciech-kulik** [comment]
It is already supported via bulk rename :D. Select multiple files and hit `r` :).

**Comment by sxyazi** [comment]
If you just want to batch rename files, Yazi already has that feature builtin, select multiple files, press `r`, and Yazi will open them in your usual editor for you to edit, then automatically rename them. I plan to add batch creation feature as well in the future, just haven't had the time yet.

As for oil, I won't implement it into Yazi directly because it works differently from Yazi’s file handling logic and would bloat the core. However, I'd love to see someone create it as a plugin - we already have [keyjump.yazi](https://github.com/mikavilpas/keyjump.yazi) (a clone of `hop.nvim`) and [searchjump.yazi](https://github.com/qsdrqs/searchjump.yazi) (a clone of `flash.nvim`), so having `oil.yazi` in the future isn't out of the question.

Closing as not on the roadmap.
