### ISSUE TITLE
Manual refresh

### ISSUE THREAD

**Issue by Daniel-Chin** [sxyazi/yazi#1356]
### Please describe the problem you're trying to solve

Other processes continuously update the dir that I'm viewing with yazi. I want to refresh the dir list (to see the changes). Currently, I can move up to the parent level and down again, but that resets the page position. 

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Provide a command to manually refresh the dir content. Optionally bind it to a key by default. 

### Additional context

Remember the old bug where removing files doesn't refresh the view ([#1330](https://github.com/sxyazi/yazi/issues/1330), [#570](https://github.com/sxyazi/yazi/discussions/570))? The manual refresh feature also makes future unforeseen refresh-related issues more tolerable. 

It should also be useful in mount/unmount situations. 

Personally, I frequently use yazi with `^Z` and `fg` in a big dir full of files. As I update the dir myself and wish to switch back to yazi to interact with the changes, manual refresh becomes a critical QoL improvement.

**Comment by sxyazi** [comment]
It's already there, just not added to the default key bindings:

```yaml
[manager]
{ on = "<C-r>", run = "refresh" }
```

Not adding it was a conscious decision because Yazi is still in its early stages and has some bugs. This way, users are encouraged to report bugs when they can't refresh files, instead of just manually refreshing and hiding the problem. 

Some bugs are platform-specific, like https://github.com/sxyazi/yazi/issues/1313, which only happens on Linux. It's not my working system, so if no one reports it, I wouldn’t know about it.

Yazi follows the "automate whenever possible" design principle, which is also well-reflected in its out-of-the-box image preview feature. Yazi always automatically chooses the best preview option for the user instead of relying on manual configuration.

Maybe I'll consider adding it to the default keys once Yazi is more stable.

**Comment by Daniel-Chin** [comment]
> It's already there, just not added to the default key bindings:
> 
> ```yaml
> [manager]
> { on = "<C-r>", run = "refresh" }
> ```
> 
> Not adding it was a conscious decision because Yazi is still in its early stages and has some bugs. This way, users are encouraged to report bugs when they can't refresh files, instead of just manually refreshing and hiding the problem.
> 
> Some bugs are platform-specific, like #1313, which only happens on Linux. It's not my working system, so if no one reports it, I wouldn’t know about it.
> 
> Yazi follows the "automate whenever possible" design principle, which is also well-reflected in its out-of-the-box image preview feature. Yazi always automatically chooses the best preview option for the user instead of relying on manual configuration.
> 
> Maybe I'll consider adding it to the default keys once Yazi is more stable.

What you said makes a lot of sense! Thanks for the explanation. Let's keep the issue closed for future reference. :+1:
