### ISSUE TITLE
Create time keep

### ISSUE THREAD

**Issue by mmuruev** [sxyazi/yazi#1364]
### Please describe the problem you're trying to solve

We discuss this already in https://github.com/sxyazi/yazi/issues/1134 but it closed. 
Yes linux has create time for more then 10years. ext4/brtrfs does support for sure and many desctop filemanagers do it also.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Keep create time on file copy. Despite the fact that this is 'new' file this is not true from user prospective. Even 'move' not always do just move but sometimes copy and remove old one.

**Comment by sxyazi** [comment]
I looked into a lot of sources:

- https://unix.stackexchange.com/a/118580
- https://unix.stackexchange.com/a/687219
- https://unix.stackexchange.com/a/336300
- https://unix.stackexchange.com/a/755589

And here's what I found:

There's no way to change the creation time of a file on Linux. So, when you copy a file, it's impossible to make the new file inherit the creation time of the old one. The creation time of the new file is set the moment it’s created, unless you have a time machine to go back and create it then.

I'm going to close this issue because it's not doable.
