### ISSUE TITLE
Don't install packages into config directory

### ISSUE THREAD

**Issue by majutsushi** [sxyazi/yazi#1408]
### `yazi --debug` output

<details>

```sh
##### ↓↓↓ Paste the output here: ↓↓↓ #####

Yazi
    Version: 0.3.0 (7a380c2 2024-08-01)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.0

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect : Kitty

Adapter
    Adapter.matches: Kitty

Desktop
    XDG_SESSION_TYPE: Some("x11")
    WAYLAND_DISPLAY : None
    DISPLAY         : Some(":0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/usr/bin/zsh")
    EDITOR             : Some("nvim")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None
    ZELLIJ_SESSION_NAME: None

Text Opener
    default: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "VIM_FORK=0 $EDITOR \"$@\"", block: true, orphan: false, desc: "VIM_FORK=0", for_: None, spread: true })

tmux
    TMUX   : false
    Version: 3.4

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-27
    fzf              : 0.46.1
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : 1.14.1
    zoxide           : 0.9.4
    7z               : 24.07
    7zz              : No such file or directory (os error 2)
    jq               : 1.7


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/jan/.local/state/yazi" directory.
```

</details>

### Please describe the problem you're trying to solve

The new package feature is quite nice, it makes it much easier to keep up with plugin updates. However, I noticed that it first clones the plugins into the `$XDG_STATE_HOME` directory and then copies them into Yazi's config directory.

I keep my configuration files under version control, and so having third-party packages pollute my own configuration makes managing that configuration more difficult. I would also have to either manually exclude all the third-party-package directories from version control or deal with large diffs every time I update plugins. It would be even better if the `package.toml` file didn't directly include the current hash (unless you want to pin it), so that updating plugins wouldn't lead to a dirty repository every time. That's one reason why other package managers make a distinction between dependency specifications and lock files.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Since the packages already exist in the state dir I think it would make sense to directly load them from there (and maybe have a lock file there as well) instead of copying them over unnecessarily.

### Validations

- [X] I have searched the existing issues
- [X] The latest nightly build of Yazi doesn't already have this feature

**Comment by sxyazi** [comment]
Duplicate of https://github.com/sxyazi/yazi/issues/1157

As I mentioned in https://github.com/sxyazi/yazi/issues/1157#issuecomment-2171049658, the `~/.config/yazi` directory is more familiar to users, which enhances the observability of plugins and makes it easier for users to review the code of the plugins they've installed. This helps to mitigate potential security issues, like those discussed in https://github.com/sxyazi/yazi/discussions/1405.

If you're using `ya pack` to manage your plugins, I recommend ignoring the entire `plugins` directory in version control.

---

>  It would be even better if the package.toml file didn't directly include the current hash (unless you want to pin it), so that updating plugins wouldn't lead to a dirty repository every time. That's one reason why other package managers make a distinction between dependency specifications and lock files.

Yes, Yazi supports pinning plugins to a specific commit (see https://github.com/sxyazi/yazi/pull/985), which is why the commit hash is included.

Currently, Yazi doesn't support lock files because I don't see the necessity for them. There's no real concept of semantic versioning here — most Yazi plugins are rolling releases. If we were to move the commit hash from `package.toml` to `package.lock`, what info would `package.toml` contain? Just a repository URL? I think that's a bit overkill if that's the only reason for it.

**Comment by SolitudeSF** [comment]
>  the ~/.config/yazi directory is more familiar to users, which enhances the observability of plugins and makes it easier for users to review the code of the plugins they've installed.

users who need the handholding to navigate to known directories arent going to review code of the plugins. this is kinda ridiculous arguments, since you would expect to review the code before installing it, if you're concerned about security. all this does now is complicates the management, because i have managed plugins that im not supposed to edit and my personal plugins in a single folder without any disambiguation.

**Comment by sxyazi** [comment]
> users who need the handholding to navigate to known directories arent going to review code of the plugins

I mean putting plugins in a noticeable directory is the simplest way to improve observability.

> since you would expect to review the code before installing it

That's a great idea, maybe we could integrate it into `ya pack`, but I don't think it conflicts with putting plugins in `~/.config/yazi`. Both of them are essentially about making plugins more transparent to users.

> because i have managed plugins that im not supposed to edit and my personal plugins in a single folder without any disambiguation

Each plugin has a globally unique name, you should differentiate them by name rather than by placing them in different directories. On the flip side, when they're all in the same directory, you can easily see which plugins you've downloaded and available.

**Comment by majutsushi** [comment]
I don't think that most people are interested in reviewing the plugin code, and if they are they are most likely going to do so before installing to check if it would work for them, rather than after.

Regarding confusion, I think it's rather more confusing to have third-party plugins and your own plugins mashed together without a clear separation about which is a managed package and which is your own code. This is especially true since every other plugin manager I can think of for tools like Vim and various shells has the managed plugins installed in their own directory.

The direct result of this is that updating plugins is no longer a one-command operation, but now every update creates extra work because the config repository becomes dirty. This is true even if you ignore the entire `plugins` directory due to the hash in the package file. Having to create a new commit after every update is exactly the kind of hassle that made me give up on git submodules for managing various plugins.

I really don't mean to come off as ungrateful, I very much appreciate all the work that has gone into this. I just feel like this system is *so close* to being perfect that it would be a shame to have to deal with this regular annoyance.

**Comment by sxyazi** [comment]
Could you propose a complete solution in detail? I will evaluate it to see if I want it and if it's easy to implement.

**Comment by majutsushi** [comment]
Based on my understanding there don't seem to be that many things that would need changing.

At a higher level I think there are only two things:
- Don't save the current plugin commit hash in `packages.toml`. Since the plugins are git repositories it is already easily possible to determine the current commit without caching it somewhere else. Pulling updates is most likely going to be much slower than the small extra step of checking the repositories for the hash, and updating is going to be a somewhat irregular and not really performance-critical operation anyway, so I don't think the additional complexity would be worth it, unless I'm missing a usecase. If you do want to save that information then I would suggest creating a `packages.toml` in the `~/.local/state/yazi/packages` directory with the same format as the current `packages.toml`, so the codepath for that could be reused.
- Load the plugins directly from `~/.local/state/yazi/packages` in addition to the ones from the config directory. I noticed that the plugins are saved in a subdirectory named after an MD5-hash of the remote. I'm not sure if that indirection is necessary since as you said plugin names are globally unique, but maybe there's something I'm missing. I'm just mentioning it because I would assume that without that indirection it should be possible to reuse the config dir plugin loading codepath.

As for the hashes that people may already have in their `packages.toml`, they could either be silently ignored, ignored with a warning, or just rewritten to remove them (explicit pins should be ignored/kept in all cases though of course).

I hope this illustrates my thoughts, please let me know if anything is unclear.

**Comment by sxyazi** [comment]
> Don't save the current plugin commit hash in packages.toml.

Then how should users install a locked version with `ya pack -i` (instead of upgrading to the latest version with `ya pack -u`) to achieve reproducibility?


> Since the plugins are git repositories it is already easily possible to determine the current commit without caching it somewhere else

No, that's not right. The plugin's hash isn't necessarily the same as the repository's hash because multiple plugins might share the same repo. For example, a user might want to install version `aaaaaa` of `chmod.yazi` and version `bbbbbb` of `full-border.yazi`, but they both belong to the [`yazi-rs/plugins` repository](https://github.com/yazi-rs/plugins).

> Pulling updates is most likely going to be much slower than the small extra step of checking the repositories for the hash, and updating is going to be a somewhat irregular and not really performance-critical operation anyway, so I don't think the additional complexity would be worth it, unless I'm missing a usecase

I didn't quite get this.


> If you do want to save that information then I would suggest creating a packages.toml in the ~/.local/state/yazi/packages directory with the same format as the current packages.toml, so the codepath for that could be reused.

If a user wants to share their Yazi configuration, would they need to upload both `~/.config/yazi` and `~/.local/state/yazi/packages` to GitHub? Because if `packages.toml` only exists in `~/.local/state/yazi/packages`, how would someone else using this config install the locked plugin versions with `ya pack -i`?

> Load the plugins directly from ~/.local/state/yazi/packages in addition to the ones from the config directory

No, like I mentioned above, the `~/.local/state/yazi/packages` directory contains the repositories, not the plugins themselves. A single repository might have multiple plugins, and different repositories might have plugins with the same name e.g. `yazi-rs/mime.yazi` and `DreamMaoMao/mime.yazi` - how would you tell these apart if they're not moved to `~/.config/yazi/plugins` during installation?

And if a user is using two different versions of two plugins from the same repository, e.g. version `aaaaaa` of `chmod.yazi` and version `bbbbbb` of `full-border.yazi`, does this mean we need to run `git checkout aaaaaa`/`git checkout bbbbbb` to switch to the correct git version every time they run a plugin?


I'm a bit confused about what you meant - when you say "Load the plugins directly from `~/.local/state/yazi/packages`", do you mean the state directory would take priority over the `~/.config` directory, so if the plugin exists in the state directory, it won't be loaded from the config directory? Or the other way around? But `~/.local/state/yazi/packages` serves as a cache, and the files inside it typically won't be deleted. Does this mean that unless the user deletes the entire `packages` directory or precisely finds and deletes the specific *whole repository* by its hash, the plugins in `~/.config/yazi/plugins` will never take effect? Or do we need to find a way to intelligently clean up these repositories, or will users need to manually clean them up periodically?

> I noticed that the plugins are saved in a subdirectory named after an MD5-hash of the remote. I'm not sure if that indirection is necessary since as you said plugin names are globally unique, but maybe there's something I'm missing. I'm just mentioning it because I would assume that without that indirection it should be possible to reuse the config dir plugin loading codepath.

Same as above, what's in `~/.local/state/yazi/packages` is the repository, not the plugin itself. The plugin itself is in `~/.config/yazi/plugins`.

**Comment by majutsushi** [comment]
Ah, I missed that repositories can contain more than one plugin.

In that case my proposal would be this: keep the current split between the repository cache and the installed plugins, and just move the directories around a bit. The current directory `$XDG_STATE_HOME/yazi/packages` would become `$XDG_STATE_HOME/yazi/packages/repositories`, and the plugins would be installed in `$XDG_STATE_HOME/yazi/packages/plugins` instead of `$XDG_CONFIG_HOME/yazi/plugins`. This way the previous behaviour would be almost completely preserved.

Although if the primary purpose of keeping the repositories around is as a cache then I think it might be more appropriate to move them to `$XDG_CACHE_HOME` instead of keeping them in the state directory. As I understand it with the current model if you deleted the packages directory then the installed plugins would keep working, and only the next update would be slower, so the cache directory seems more appropriate to me. This would also make it easier to exclude the repositories from backups.

As for reproducibility, if we actually want full reproducibility (instead of just being able to pin specific plugins) then instead of using the `package.toml` I proposed in my previous comment we could have an actual `lockfile.toml` in `$XDG_CONFIG_HOME/yazi`. This would have the same format as the current `package.toml` (except only with pure hashes, no "pins") and would be the file used for `ya pack -i`. The current `package.toml` would only contain explicit (optional) pins.

So as an example, this would be `package.toml` (reformatted a bit):

```
[plugin]
deps = [
	{ use = "user1/plugin1" },
	{ use = "user2/myplugins#plugin2" },
	{ use = "user2/myplugins#plugin3", commit = "=abc123" }
]
```

And this would be `lockfile.toml`:

```
[plugin]
deps = [
	{ use = "user1/plugin1", commit = "ababab" },
	{ use = "user2/myplugins#plugin2", commit = "xyxyxy" },
	{ use = "user2/myplugins#plugin3", commit = "abc123" }
]
```

With this approach people can decide whether they want to commit the lockfile to version control and deal with creating a new commit after every update, or ignore the file and only having to create a commit if they change the installed plugins. This would make it very similar to normal language package managers. And if someone wants to share their configuration they share either only `package.toml` or both files depending on whether reproducibility is relevant.

> > Don't save the current plugin commit hash in packages.toml.
> 
> Then how should users install a locked version with `ya pack -i` (instead of upgrading to the latest version with `ya pack -u`) to achieve reproducibility?

To be honest I don't think I've ever seen a situation where a lockfile for reproducibility for such a tool was really necessary, which is why I don't think many other tool package managers have them. But the approach I outlined above would keep this functionality in what I think is a simple way.

> > Pulling updates is most likely going to be much slower than the small extra step of checking the repositories for the hash, and updating is going to be a somewhat irregular and not really performance-critical operation anyway, so I don't think the additional complexity would be worth it, unless I'm missing a usecase
> 
> I didn't quite get this.

This was based on my assumption that the hashes in `package.toml` were mostly for caching purposes, and thinking that this seemed like an unnecessary optimization to me. But since they're meant for reproducibility this sentence doesn't really apply any more.

> I'm a bit confused about what you meant - when you say "Load the plugins directly from `~/.local/state/yazi/packages`", do you mean the state directory would take priority over the `~/.config` directory, so if the plugin exists in the state directory, it won't be loaded from the config directory? Or the other way around? But `~/.local/state/yazi/packages` serves as a cache, and the files inside it typically won't be deleted. Does this mean that unless the user deletes the entire `packages` directory or precisely finds and deletes the specific _whole repository_ by its hash, the plugins in `~/.config/yazi/plugins` will never take effect? Or do we need to find a way to intelligently clean up these repositories, or will users need to manually clean them up periodically?

My thinking was that when running an install or update command the tool would automatically clean up repositories for plugins that were no longer configured in `package.toml`, similar to what other package managers do. But if the repository cache were moved to `$XDG_CACHE_HOME` then this would not be necessary because people can just delete the entire cache directory if they want to free up space.

**Comment by sxyazi** [comment]
Basically, this is just duplicating the existing `~/.config/yazi/plugins` directory and `package.toml` file. It just makes the existing structure more complicated, turning two directories into three and one `toml` file into two. I don't see how this makes things simpler for maintenance or users:

- It breaks the convention for the plugin directory: For a long time, the Yazi plugin directory was just `~/.config/yazi/plugins`. Now, we'd need to add a `state` directory as another plugin directory, meaning plugins could come from either of these two.
- We'd need to introduce the concept of priority and explain it to users everywhere that deals with plugin paths.
- It makes it harder for users to uninstall plugins: Before, if they didn't need a plugin, they'd just delete its directory under `~/.config/yazi/plugins`. Now, they'd have to delete it from two directories.
- `YAZI_CONFIG_HOME` won't work properly: Even if users set a different `YAZI_CONFIG_HOME`, they might still end up loading plugins from `~/.config/yazi/state`.
- And all these problems apply to flavors as well.

And it goes against the design of `ya pack`:

- `ya pack` was just automating the process of users manually downloading plugins from GitHub to `~/.config/yazi/plugins`. The Yazi plugin directory has always been `~/.config/yazi/plugins`, I'm not sure why it's become an issue now that we have a more automated package manager. It should manage files in `~/.config/yazi` the same way it always has - if people want to include it in version control, they add it, or they exclude it with `.gitignore`.
- `ya pack` assumes most users want to pin versions, so it saves the hash in the `toml` instead of updating to a random latest version every time you run `ya pack -i` as that would just surprise users, not give them what they expect. If you don't need that, it probably doesn't fit your workflow, and honestly, a simple shell script with `git clone` might be enough — it could clone the latest plugin version every time.

Just for the record, Yazi's goal has never been to be perfect, or to create a tool that works for everyone. That would not only make it insanely complex, but it'd also add a ton of extra maintenance work. The fact is, I've been making trade-offs and rejecting features that I don't think should be part of Yazi. 

I really appreciate your detailed explanation of what you're looking for, and I do understand your needs, but I just think `ya pack` might not really fit your workflow - it's just a tool that automates the download process, you could also easily implement it yourself with some shell scripts, or use community options, like the [package manager included in `yazi.nvim`](https://github.com/mikavilpas/yazi.nvim/blob/main/documentation/plugin-management.md) if you're using Neovim.

**Comment by majutsushi** [comment]
That's a shame, but thanks for hearing me out. I can certainly understand not being able to make everyone happy, I have experience with that myself.

Would it at least be possible to have a second directory to load plugins from, so that people can manage that directory themselves? It wouldn't be used by anything official, and I don't really care about the priority, but this would make it at least possible to install third-party plugins yourself without having to individually ignore them in Git.
