### ISSUE TITLE
ya pack download path specify ourselves

### ISSUE THREAD

**Issue by AnirudhG07** [sxyazi/yazi#1516]
### `yazi --debug` output

```Shell
not required
```

### Please describe the problem you're trying to solve

I have ya pack download to my ~/.config/yazi, but I have my dotfiles configured in some other files, through where I symlink to ~/.config/yazi.
So if we can specify a config file (or some other way) where ya pack knows to download there instead of ~/.config/yazi, currently I am either manually installing it or cutting pasting it.

### Would you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

Some config file, where `ya` can have its configurations set, including location to download in. Maybe this can open up more possible options for expansion of ya(I donno). 
For ex, this can also help in expanding to other domains as mentioned in one of the issues, that ya needs to expand more for other websites. For example, the config file can have the location/branch/dir for gitee/github, etc to specify `ya` for a plugin or other packages, that users can change acc to themselves(for non standard usages). Or something similar.

### Additional context

I would need guidance to help out, since I dont know where to start/noob at Rust.

### Validations

- [X] I have searched the existing issues
- [X] The latest nightly build of Yazi doesn't already have this feature

**Comment by sxyazi** [comment]
> I have my dotfiles configured in some other files, through where I symlink to ~/.config/yazi

If I understand correctly, your `yazi.toml`, `keymap.toml`, and other files aren't in `~/.config/yazi` but in another directory, let's say `/a`. Then you link `/a/keymap.toml` to `~/.config/yazi/keymap.toml`, right? 

If that's the case, I think you should use `YAZI_CONFIG_HOME` to set `/a` directly as Yazi's config directory, like `YAZI_CONFIG_HOME=/a`, instead of linking them to `~/.config/yazi`.

Doc of `YAZI_CONFIG_HOME`: https://yazi-rs.github.io/docs/configuration/overview#custom-directory

**Comment by AnirudhG07** [comment]
Yep it works! Thanks so much!
