### ISSUE TITLE
Add "linktoexec" as a "is" condition

### ISSUE THREAD

**Issue by PoisonFrog** [sxyazi/yazi#1518]
### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.1 (Arch Linux 2024-08-17)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.1 (Arch Linux 2024-08-17)

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect : Kitty

Adapter
    Adapter.matches: Kitty

Desktop
    XDG_SESSION_TYPE: Some("x11")
    WAYLAND_DISPLAY : None
    DISPLAY         : Some(":0.0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/usr/bin/zsh")
    EDITOR             : Some("nvim")
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : 3.4
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : 2.9.6
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-36
    fzf              : 0.54.3
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : 1.14.2
    zoxide           : 0.9.4
    7z               : 17.05
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1
```

### Please describe the problem you're trying to solve

Right now with Yazi we can color files that link to an executable with the same color as a regular executable or the same color of a regular link. I'm trying to emulate the theme I had in ranger with symlinks being cyan, executables being bold green, and symlinks that are linking to an executable are bold cyan to differentiate them from a regular executable or link. Unfortunately this is not possible in Yazi right now.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

I think a good solution would be to create an `is` condition called `linktoexec` or something like that so people that want to differentiate their symlinks that link to an executable from a regular link or executable can do that.

### Validations

- [X] I have searched the existing issues
- [ ] The latest nightly build of Yazi doesn't already have this feature

**Comment by sxyazi** [comment]
It's totally possible; you just need to override the [`Entity.style`](https://github.com/sxyazi/yazi/blob/0f106b591c7be48508821313a6b2a9566f8dca62/yazi-plugin/preset/components/entity.lua#L84) method and layer on any conditions you want, like this:

```lua
local old_style = Entity.style
Entity.style = function(self)
  local cha, sty = self._file.cha, old_style(self)
  if sty and cha.is_link and cha.is_exec and not cha.is_dir then
    sty:patch(ui.Style():bold():fg("cyan"))
  end
  return sty
end
```

![screenshot-001970](https://github.com/user-attachments/assets/1b3c582a-d217-4f8e-ab40-4629ab4526ff)

- Doc of `Cha`: https://yazi-rs.github.io/docs/plugins/types#shared.cha
- Doc of `Style`: https://yazi-rs.github.io/docs/plugins/layout#style

---

BTW I plan to redesign the filetype handling in Yazi v0.4, similar to [how icons work](https://yazi-rs.github.io/docs/configuration/theme#icon), using `cond` instead of `is`. When that's done, you'll be able to achieve this in toml as well.
