### ISSUE TITLE
Word wrap configuration option changes

### ISSUE THREAD

**Issue by uncenter** [sxyazi/yazi#1555]
### `yazi --debug` output

```Shell
N/A
```

### Please describe the problem you're trying to solve

The recently merged https://github.com/sxyazi/yazi/pull/1159 adds word wrapping to the preview, but the option is poorly named and designed. The two values for the option are `"yes"` and `"no"`, two strings, instead of a boolean. Additionally, everywhere I can find the word "wrap" mentioned in the pull request except for in the naming of the option, "wrap" is preceded by "word wrap".

### Would you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

To clarify the option, it should be called `word_wrap` instead of `wrap` and accept a boolean instead of yes/no strings.

### Validations

- [X] I have searched the existing issues
- [X] The latest nightly build of Yazi doesn't already have this feature

**Comment by sxyazi** [comment]
> The two values for the option are "yes" and "no", two strings, instead of a boolean

This is a deliberate decision. Using a string instead of a boolean is to allow for the addition of other wrapping behaviors in the future. As I mentioned in that PR, it's still unstable and will be adjusted accordingly as `ratatui` implements these features.

For example, CJK (Chinese, Japanese, Korean) languages require different line wrapping (See https://github.com/ratatui/ratatui/issues/1199), which can't be represented with just a boolean:

```toml
wrap = "cjk"
```

---

> Additionally, everywhere I can find the word "wrap" mentioned in the pull request except for in the naming of the option, "wrap" is preceded by "word wrap"

This is also a deliberate decision, allowing us to add options like [`wrap_trim`](https://docs.rs/ratatui/latest/ratatui/widgets/struct.Wrap.html#structfield.trim) or even [`wrap_indent`](https://github.com/ratatui/ratatui/issues/284) in the future without making the name too long (like `word_wrap_trim` or `word_wrap_indent`), which is both ugly and doesn't fit Yazi's naming aesthetics. As you can see, all options in `yazi.toml` (or even `theme.toml`, `keymap.toml`) are made up of a maximum of two words.

---

Note that the things I mentioned above (except for `wrap_trim`) haven't been implemented in `ratatui` yet. I'm just reserving these options now so that we can expand in the future without causing any breaking changes.
