### ISSUE TITLE
Override only specified keymaps rather than specifying all of it

### ISSUE THREAD

**Issue by sabitm** [sxyazi/yazi#158]
Hi, thanks for this awesome project!

Is it possible to specify only some keymaps in `keymap.toml` and make it override the said keymaps and make others default?
The use case is when I have to override only `J` and `K` keys so I have to only specify this in `keymap.toml`:

```toml
[manager]

keymap = [
    { on = [ "K" ], exec = "arrow -25", desc = "Move cursor up 25 lines" },
    { on = [ "J" ], exec = "arrow 25",  desc = "Move cursor down 25 lines" }
]

```

**Comment by sxyazi** [comment]
Hey @sabitm, since Yazi is still in the alpha stage and is not yet stable, default keybindings may undergo adjustments, potentially disrupting user expectations.

Therefore, I encourage users to copy the complete keybinding list, which will not be affected by default configurations. Considering a merge after Yazi stabilizes seems to make more sense.

**Comment by sabitm** [comment]
Oh, that's definitely make sense
I'll be using the complete list then. for now
Thanks!
