### ISSUE TITLE
environment variables accessible in `shell` commands

### ISSUE THREAD

**Issue by Maik93** [sxyazi/yazi#1635]
### `yazi --debug` output

```Shell
none.
```

### Please describe the problem you're trying to solve

Currently, the `shell` command (https://yazi-rs.github.io/docs/configuration/keymap/#manager.shell) does not support linux environment variables. They would be very helpful when dealing with complex keybindings.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

I'd like to write keymaps such as `run = "shell --orphan --confirm 'if [[ -n $TMUX ]]; then ...`

### Validations

- [X] I have searched the existing issues
- [X] The latest nightly build of Yazi doesn't already have this feature

**Comment by sxyazi** [comment]
Hi, this is a feature that's already supported, I have:

``` 
{ on = "<C-t>", run = "shell --orphan --confirm 'echo $TMUX > /tmp/test'" }, 
```

in my keymap.toml, when I press `<C-t>`, the value of `$TMUX` is correctly output to `/tmp/test`:

```
❯ cat /tmp/test
/private/tmp/tmux-501/default,74392,2
```

I'm not sure what version of Yazi you're using since you skipped `yazi --debug`, but please make sure it's the latest version.

Closing as already supported.

**Comment by Maik93** [comment]
I'm not sure what I was missing, but your keymap snippet actually works both for me!

Thanks, please keep going on with this repo because it's beautiful!
