### ISSUE TITLE
Copy file contents to clipboard

### ISSUE THREAD

**Issue by braykov** [sxyazi/yazi#1671]
### `yazi --debug` output

```Shell
It's a proposal, not a problem
```

### Please describe the problem you're trying to solve

It is often needed to copy a text file contents to the clipboard

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

For a single selection only.
Use the shortcut `cc` to copy contents.

### Additional context

As `cc` is currently for copying path to clipboard, introduce a (breaking) change:
Make `cp` shortcut to copy path.
When used over a directory, copy the directory (top level) file list in the clipboard.

### Validations

- [X] I have searched the existing issues
- [X] The latest nightly build of Yazi doesn't already have this feature

**Comment by sxyazi** [comment]
Please use a plugin like https://github.com/orhnk/system-clipboard.yazi, which is a wrapper for [`ClipBoard`](https://github.com/Slackadays/ClipBoard).

Building this into Yazi would require implementing it for three different systems (Linux, macOS, Windows), which essentially means re-implementing the `ClipBoard` from scratch. This is not trivial and would bloat Yazi, while also overlapping somewhat with Yazi's built-in `yank` feature.

If users really need this, using the clipboard plugin might be a better solution since it would be on-demand rather than mandatory.

Closing as no plans to build it in, and a plugin provides this feature already exists.

**Comment by sxyazi** [comment]
BTW you can find more awesome plugins at https://yazi-rs.github.io/docs/resources

**Comment by braykov** [comment]
The plugin mentioned copies the file to the clipboard, so the file is pasted elsewhere.
This suggestion is for copying files contents, similar to `cat file.txt | pbcopy`.
But, I agree with your explanation for rejection.

**Comment by sxyazi** [comment]
If `cat file.txt | pbcopy` works for you, you can easily achieve this with the [`shell`](https://yazi-rs.github.io/docs/configuration/keymap/#manager.shell) command:

```toml
[[manager.prepend_keymap]]
on  = "<C-y>"
run = '''
    shell 'cat "$0" | pbcopy' --confirm
'''
```
