### ISSUE TITLE
Uzing shell prompt (; - key binding) with command sudo causing crashes of gui and strange random events while asking for password.

### ISSUE THREAD

**Issue by jagerem** [sxyazi/yazi#1686]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

kitty 0.36.1 

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (7222e17 2024-09-19)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: No such file or directory (os error 2)

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect : Kitty

Adapter
    Adapter.matches: Kitty

Desktop
    XDG_SESSION_TYPE           : Some("tty")
    WAYLAND_DISPLAY            : None
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/bin/bash")
    EDITOR             : Some("micro")
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : No such file or directory (os error 2)
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.44
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.3
    magick           : No such file or directory (os error 2)
    fzf              : 0.55
    fd               : No such file or directory (os error 2)
    rg               : 14.1.1
    chafa            : No such file or directory (os error 2)
    zoxide           : 0.9.4
    7z               : 24.08
    7zz              : No such file or directory (os error 2)
    jq               : 1.7
```

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

Uzing shell prompt (: - key binding) with command sudo causing crashes of gui and bugy random events while asking for password.

### Minimal reproducer

Using the key bindings ";" when prompt "shell" will appear run for example sudo rm <some file> on the right side of the column will be displayed the info "password user <user name>" next when you move a mouse for instance, there will be displayed the numbers and when you provide the password sometimes it is working properly - but this is rare situation - more often you will get some crashes or text editor will be open etc. This happens only for first time using the sudo in current terminal session In case you will success, still the name of the file keeps appear.

**Comment by sxyazi** [comment]
This is expected behavior, `sudo` is an interactive program that requires password input, and it will compete for I/O signals with Yazi, including keyboard input and TTY resources (TUI rendering). 

So you should run it interactively using `;` instead of `:`. Also, use `sudo rm "$1"` instead of just `sudo rm`, as this isn't a complete shell command since the file path isn't passed to `rm`. 

https://github.com/user-attachments/assets/6b47cd07-9e7a-4b10-bb40-83e0c37829d0

Doc of the `shell` command: https://yazi-rs.github.io/docs/configuration/keymap/#manager.shell

---

If you want to skip the `$1` parameters, use this https://github.com/Ape/open-with-cmd.yazi plugin.

BTW a better way to do `sudo` is to use a plugin like https://github.com/TD-Sky/sudo.yazi

You can find more awesome plugins at https://yazi-rs.github.io/docs/resources

**Comment by jagerem** [comment]
Thank you very much for your detailed response!!!!!!!!
Your Yazi is awesome!!!!!!!
I wrote some scripts and now I even get automounting feature like in GUI file managers for example Thunar.
Good luck to you and all Guys working on Yazi development.
