### ISSUE TITLE
yazi ignoring mime databaze because it is using `file`

### ISSUE THREAD

**Issue by WizardUli** [sxyazi/yazi#1731]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

Alacritty

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (Nixpkgs 2024-09-04)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.3 (Nixpkgs 2024-09-04)

Emulator
    Emulator.via_env: ("xterm-256color", "")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect : Unknown([])

Adapter
    Adapter.matches: Wayland

Desktop
    XDG_SESSION_TYPE           : Some("wayland")
    WAYLAND_DISPLAY            : Some("wayland-1")
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : Some("/run/user/1000/sway-ipc.1000.2088.sock")
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/run/current-system/sw/bin/fish")
    EDITOR             : Some("hx")
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : No such file or directory (os error 2)
    ZELLIJ_SESSION_NAME: None
    Zellij version     : 0.40.1

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-38
    fzf              : 0.55.0
    fd               : 10.2.0
    rg               : 14.1.1
    chafa            : 1.14.4
    zoxide           : 0.9.6
    7z               : No such file or directory (os error 2)
    7zz              : 24.08
    jq               : 1.7.1
```

### Did you try the latest nightly build to see if the problem got fixed?

No, and I'll explain why below

### Describe the bug

Yazi is using `file` utility to obtain MIME type of files which is then used e.g. to choose correct _opener_ etc.
The `file` utiltiy does not seem to be querying MIME database at all. (Unfortunately I'm not 100% sure but at least ordinary Fedora and a little less ordinary NixOS both behave that way.)
Therefore it returns incorrect results compared to e.g. `xdg-mime query filetype` and yazi matches incorrect rule...

The responsible code is clearly there even in nightly build: https://github.com/sxyazi/yazi/blob/8c5d8aa5893529cf73929b7955fb7182a0df8ac5/yazi-plugin/preset/plugins/mime.lua#L19

### Minimal reproducer

On clear standard desktop installation of Fedora (40):
- Install OpenSCAD via `sudo dnf install openscad`. The problem has nothing to do with it except that it is a good example of an **application that installs its own MIME types**.
- Download this file https://github.com/openscad/openscad/blob/master/examples/Basics/CSG.scad
- Use the default rules https://github.com/sxyazi/yazi/blob/7c445cef1fd9ff9d41314d3d2b02cbc74250c6bf/yazi-config/preset/yazi.toml#L60 Point is that `text/plain` has higher priority and do something different than `application/x-openscad`.
- Observe that yazi treats the file above as `text/plain` even though `xdg-mime query filetype CSG.scad` clearly returns `application/x-openscad`.

**Comment by sxyazi** [comment]
This is expected behavior because Yazi doesn't know if the user has the dedicated program OpenSCAD for `*.scad` files. So Yazi will do its best to handle it "correctly" by treating it as a text file preview and opening it in a text editor, since it is indeed a valid text file that doesn't contain binary content.

Of course, this won't satisfy all users, which is why we also [provide a `name` rule](https://yazi-rs.github.io/docs/configuration/yazi#open) — it matches filename using a glob expr, rather than mime-types. Ples, we expose the mime-type API for users who truly need `xdg-mime`; the [`mime-ext.yazi` plugin](https://github.com/yazi-rs/plugins/tree/main/mime-ext.yazi) is an example of this.

As for using `file` instead of `xdg-mime`, the `file` command not only checks file extensions but also examines file content, making it *generally* more accurate. It handles files like `.prettierrc`, which have no extension, very well — `file` will correctly return `application/json` instead of `text/plain`.

Additionally, `file` is more readily available. Yazi is cross-platform software; most Linux distributions have `file`, and macOS, being a BSD system, also includes it. For Windows users, as long as they install "Git for Windows", they can use the `file.exe` that comes with it. I'm not sure if macOS and Windows users can use `xdg-mime`.

**Comment by SolitudeSF** [comment]
> As for using file instead of xdg-mime, the file command not only checks file extensions but also examines file content, making it generally more accurate.

not really, xdg-mime also checks file content, `file` is only more accurate in edge-cases like json in `.prettierrc`.
