### ISSUE TITLE
type stubs

### ISSUE THREAD

**Issue by Axlefublr** [sxyazi/yazi#1769]
As I was writing [my plugin](https://github.com/Axlefublr/harp.yazi), I naturally came to writing out [type stubs](https://github.com/Axlefublr/harp.yazi/blob/main/types.lua) to get lua language server completions.

Is this already a thing somewhere we could conveniently copy from? I think having lsp completions for plugin developers would be beneficial. Great docs btw! Somehow better than my window manager's.

**Comment by sxyazi** [comment]
Unfortunately, there hasn't been much progress on this lately. Most methods and types are defined on the Rust side, and currently, there doesn't seem to be a good way to generate type definitions from them. 

I don't have enough time to maintain another set of documents besides the existing documentation, as it would double my workload, leaving me constantly struggling between Rust implementation, documentation, and Lua definitions. 

Perhaps we can revisit the possibility of finding a better way to maintain them once the plugin system stabilizes. For now, the plugin system is still in beta, meaning the API isn't fully finalized. 

I'm going to close this since it duplicates https://github.com/sxyazi/yazi/discussions/981

**Comment by Axlefublr** [comment]
> there doesn't seem to be a good way to generate type definitions from them.

Oh duh! it didn't come to my mind that they would have to be generated, for some reason I thought they would infinitely remain the same. My idea was to maybe make the community PR the types in, bit by bit, but considering that things would change, the suggestions would end up being not just incomplete, but often outdated. Which ends up being more harmful than useful :c

> I don't have enough time to maintain another set of documents

Yeah super understandable. You're doing great work already! :D

Thank you very much for such a patient and kind response :3
