### ISSUE TITLE
Dynamic column_ratio following the available width of the terminal at that time

### ISSUE THREAD

**Issue by luccahuguet** [sxyazi/yazi#1809]
### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (VERGEN_IDEMPOTENT_OUTPUT 2024-10-19)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.1 (VERGEN_IDEMPOTENT_OUTPUT 2024-08-25)

Emulator
    Emulator.via_env: ("xterm-256color", "WezTerm")
    Emulator.via_csi: Ok(Unknown([Sixel]))
    Emulator.detect : WezTerm

Adapter
    Adapter.matches: Sixel

Desktop
    XDG_SESSION_TYPE           : Some("wayland")
    WAYLAND_DISPLAY            : Some("wayland-1")
    DISPLAY                    : Some(":1")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/home/lucca/.cargo/bin/nu")
    EDITOR             : Some("/home/lucca/user_installs/helix/target/release/hx")
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : tmux 3.2a
    ZELLIJ_SESSION_NAME: Some("gracious-xylophone")
    Zellij version     : 0.40.1

Dependencies
    file             : 5.41
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: No such file or directory (os error 2)
    magick           : No such file or directory (os error 2)
    fzf              : 0.29
    fd               : No such file or directory (os error 2)
    rg               : No such file or directory (os error 2)
    chafa            : 
    zoxide           : 0.9.4
    7z               : 16.02
    7zz              : No such file or directory (os error 2)
    jq               : 1.6


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/lucca/.local/state/yazi" directory.
```

### Please describe the problem you're trying to solve

There are multiple times when the width of the pane or window that yazi is in changes

Sometimes it takes the whole screen, sometimes it even acts as sidebar! (in projects like https://github.com/luccahuguet/yazelix)

So with the ratio fixed, precious space gets "wasted" when more adapted ratios could be used

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Now, imagine if yazi could auto-tune the ratio as the screen width changes...

- with a whole screen to half-screen availble: default-ratio of [1, 4, 3]
- half-screen to a third of screen availble: [1, 4, 0]
- a third of screen to smaller availble: [0, 1, 0]

That would be amazing

Now, this is just an example, you'll probably find better rules than me (or even make it user-configurable) but it would be lit nevertheless

### Validations

- [X] I have searched the existing issues/discussions
- [X] The latest nightly build of Yazi doesn't already have this feature

**Comment by sxyazi** [comment]
Sorry, there are no plans to build this feature in because it's hard to say what proportion is truly suitable for users, and whether they really want to dynamically adjust the layout based on that proportion. Some users might prefer it to always be present or to adjust it with a key press.

However, this can be easily implemented with a plugin; you just need to rewrite the [`Tab.layout` method](https://github.com/sxyazi/yazi/blob/24a77d8a5f07f15d3b7d4651c9acf1e372ea5aef/yazi-plugin/preset/components/tab.lua#L12-L21) and apply your layout configuration based on `self._area`, which is a [`ui.Rect`](https://yazi-rs.github.io/docs/plugins/layout#rect), for example:


```lua
Tab.layout = function(self)
  self._chunks = ui.Layout()
    :direction(ui.Layout.HORIZONTAL)
    :constraints({
      ui.Constraint.Ratio(1, 8),  -- parent, change to whatever you want
      ui.Constraint.Ratio(4, 8),  -- cwd, change to whatever you want
      ui.Constraint.Ratio(3, 8),  -- preview, change to whatever you want
    })
    :split(self._area)
end
```

There are also two similar plugins for your reference: 

- https://github.com/yazi-rs/plugins/tree/main/max-preview.yazi
- https://github.com/yazi-rs/plugins/tree/main/hide-preview.yazi

See docs at:

- Doc of `ui.Layout()`: https://yazi-rs.github.io/docs/plugins/layout#layout
- Doc of `ui.Constraint()`: https://yazi-rs.github.io/docs/plugins/layout#constraint

Closing as the layout API for implementing them has already been provided through the plugin system.

**Comment by luccahuguet** [comment]
Thank you so much

The plugins seem very useful for yazelix

💫
