### ISSUE TITLE
Magnify preview on files when pressing <Right>

### ISSUE THREAD

**Issue by tesar-tech** [sxyazi/yazi#2021]
### `yazi --debug` output

```Shell
N/A
```

### Please describe the problem you're trying to solve

Currently, when previewing a file, there is no built-in way to quickly magnify the preview for better visibility. Although a [plugin](https://github.com/yazi-rs/plugins/blob/main/max-preview.yazi/init.lua) exists to achieve this functionality, it feels cumbersome to press another shortcut to step into and out of the "preview magnification". Additionally, pressing `<Right>` on a single file currently performs no action, leaving an opportunity to enhance its usability.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

I propose allowing the `<Right>` action to magnify the preview of a single file. This would provide a simple, intuitive way to enhance the preview without requiring additional plugins or configurations. It leverages an existing keybinding that is currently underutilized in this context, making the functionality more accessible and seamless. And of course <Left> on magnified preview would go back to the "3-pane state".

### Checklist

- [X] I have searched the existing issues/discussions
- [X] The [latest nightly build](https://yazi-rs.github.io/docs/installation/#official-binaries) doesn't already have this feature

**Comment by sxyazi** [comment]
`<Right>` has already been bound to `Enter` – it currently has no effect on files because that part of the functionality [hasn't been developed yet](https://yazi-rs.github.io/docs/faq#why-separate-open-enter), but it is a reserved key:

https://github.com/sxyazi/yazi/blob/0b340b67d5621402c50de264d8bf82e9aa4e2759/yazi-config/preset/keymap-default.toml#L40

Also, if you use `<Right>` to zoom in, how do you zoom out/restore? Is it `<Left>`? But that's already used to go back to the previous directory. 

If you press `<Right>` again to restore, that would exactly be the functionality provided by the [max-preview.yazi](https://github.com/yazi-rs/plugins/tree/main/max-preview.yazi) plugin already. Why not just bind your `<Right>` key to this plugin if you really want your `<Right>` to do this?

```toml
[[manager.prepend_keymap]]
on   = "<Right>"
run  = "plugin max-preview"
desc = "Maximize or restore preview"
```

**Comment by tesar-tech** [comment]
> Also, if you use `<Right>` to zoom in, how do you zoom out/restore? Is it `<Left>` ? But that's already used to go back to the previous directory.

Yes, it's `<Left>`. It would have to somehow detect it's in "zoomed preview" and escape from that on `<Left>`. Maybe it's doable with plugin, but I am not aware of that...

> Why not just bind your <Right> key to this plugin if you really want your <Right> to do this?

Because on directories pressing `<Right>` will open the preview instead of entering the directory.

**Comment by sxyazi** [comment]
> Yes, it's `<Left>`. It would have to somehow detect it's in "zoomed preview" and escape from that on `<Left>`. Maybe it's doable with plugin, but I am not aware of that...

No, this would disrupt the current user interaction. Some users who don't use Vim-like `hjkl` navigation rely on the arrow keys for navigation.

> Because on directories pressing `<Right>` will open the preview instead of entering the directory.

If you want to handle directories differently, you just need to check if it's a directory using `is_dir`, and can be easily implemented via a plugin system. Here's an example: https://github.com/yazi-rs/plugins/blob/ec97f8847feeb0307d240e7dc0f11d2d41ebd99d/smart-enter.yazi/init.lua#L7

**Comment by sjLambda** [comment]
Zoom or full screen feature for the preview is highly desirable. As for which shortcuts to implement, that can be trashed out. Actually a toggle key to full screen and back would be a good UI fit.
