### ISSUE TITLE
Use xdg-mime instead of file for detecting file type

### ISSUE THREAD

**Issue by matejdro** [sxyazi/yazi#2076]
### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (Arch Linux 2024-09-05)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.3 (Arch Linux 2024-09-05)

Emulator
    Emulator.via_env: ("xterm-256color", "")
    Emulator.via_csi: Ok(Konsole)
    Emulator.detect : Konsole

Adapter
    Adapter.matches: KittyOld

Desktop
    XDG_SESSION_TYPE           : Some("wayland")
    WAYLAND_DISPLAY            : Some("wayland-1")
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: Some("12f9a0d0b93f691d4d9923716557154d74777b0a_1734764072_1164993843")
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/usr/bin/zsh")
    EDITOR             : Some("code -w")
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "code \"$@\"", block: false, orphan: true, desc: "code", for_: None, spread: true })
    block  : Some(Opener { run: "code -w \"$@\"", block: true, orphan: false, desc: "code (block)", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : No such file or directory (os error 2)
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.46
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.3
    magick           : 7.1.1-41
    fzf              : 0.56.3
    fd               : 10.2.0
    rg               : 14.1.1
    chafa            : No such file or directory (os error 2)
    zoxide           : 0.9.6
    7z               : 17.05
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/matej/.local/state/yazi" directory.
```

### Please describe the problem you're trying to solve

From what I can see, `xdg-mime` seems to be more accurate than `file` when it comes to detecting file types. This seems to be mostly the case with the various zip files, such as epub (https://github.com/sxyazi/yazi/issues/1062), where `file` would detect some epubs as just a regular zip or even a regular zip that `file` sometimes detects just as `data`.

According to the https://wiki.archlinux.org/title/Xdg-utils#xdg-mime, in the worst case scenario `xdg-mime` just falls back to `file`, so I think it should work better in most cases and in the worst case be the same as just using `file` directly.

### Would you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

If the computer has `xdg-mime` installed, use `xdg-mime query filetype $0` instead of `file $0` to get the mime type of the file

### Checklist

- [X] I have searched the existing issues/discussions
- [X] The [latest nightly build](https://yazi-rs.github.io/docs/installation/#official-binaries) doesn't already have this feature

**Comment by matejdro** [comment]
It seems like a similar issue was opened here: #1731, but then closed prematurely on the assumption that `xdg-mime` only uses file extension, which is not the case, as mentioned by the (unanswered) comment.

**Comment by sxyazi** [comment]
The issue with `xdg-mime` is that it's not cross-platform — how can it be used on macOS, Windows, or Android? Yazi is cross-platform, and I want to avoid introducing platform-specific software as much as possible.

I also don't think supporting both `file` and `xdg-mime` is an option, because Yazi's default config is specific to `file(1)` — whenever we add a new mimetype, we check the source code of `file(1)` and align with it, just like we did in https://github.com/sxyazi/yazi/pull/1926. Supporting `xdg-mime` would mean maintaining two different configs, which would make things unnecessarily complicated.

Another issue is that I don't think `xdg-mime` can be used as a "stable" mimetype provider. I briefly looked at [the code](https://cgit.freedesktop.org/xdg/xdg-utils/tree/scripts/xdg-mime.in), and it just goes through various system-installed software to determine a file's mimetype, such as `kmimetypefinder`, `gio`, `gvfs-info`, `gnomevfs-info`, `qtxdg-mat`, `mimetype`, `file`, etc.

This means that users with the same Yazi config might not get the same expected behavior across different systems. For example, `kmimetypefinder` is specific to KDE, while `gio` is specific to GNOME, so if a user switches their desktop environment, the same Yazi config might not work. Not to mention, any version changes in any of those software tools could break things. 

Different versions of `xdg-mime` itself might have different behaviors as well. We've already spent a lot of time and effort unifying the behavior of different `file(1)` versions (like in https://github.com/sxyazi/yazi/pull/1927 and https://github.com/sxyazi/yazi/pull/1995), and I really don't want to go through that again.

Especially considering you can easily add support for `xdg-mime` through the plugin system, and I [encourage users to use different mime providers](https://yazi-rs.github.io/docs/tips#make-yazi-even-faster) based on their needs. Yazi's built-in mime plugin is just a baseline.
