### ISSUE TITLE
Wierd tmux behaviour

### ISSUE THREAD

**Issue by dangooddd** [sxyazi/yazi#2106]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

alacritty 0.14.0

### `yazi --debug` output

```Shell
Yazi
    Version: 0.4.3 (d754ac5d 2024-12-27)
    Debug  : false
    Triple : x86_64-unknown-linux-gnu (linux-x86_64)
    Rustc  : 1.83.0 (90b35a62 2024-11-26)

Ya
    Version: 0.4.3 (d754ac5d 2024-12-27)

Emulator
    Brand.from_env      : None
    Emulator.detect     : Emulator { kind: Right(Unknown { kgp: false, sixel: false }), light: false, cell_size: None }
    Emulator.detect_full: Ok(Emulator { kind: Right(Unknown { kgp: false, sixel: false }), light: false, cell_size: None })

Adapter
    Adapter.matches: Chafa

Desktop
    XDG_SESSION_TYPE           : Some("wayland")
    WAYLAND_DISPLAY            : Some("wayland-0")
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

NVIM
    NVIM          : false
    Neovim version: 0.10.2

Variables
    SHELL           : Some("/bin/bash")
    EDITOR          : Some("nvim")
    VISUAL          : Some("nvim")
    YAZI_FILE_ONE   : None
    YAZI_CONFIG_HOME: None
    YAZI_ZOXIDE_OPTS: None
    FZF_DEFAULT_OPTS: Some("--layout=reverse                          --height 10                          --ansi                          --border=sharp")

Text Opener
    default     : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block-create: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block-rename: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : 2
    tmux version       : tmux 3.5a
    tmux build flags   : enable-sixel=Unknown
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file          : 5.45
    ueberzugpp    : No such file or directory (os error 2)
    ffmpeg/ffprobe: 7.0.2 / 7.0.2
    pdftoppm      : 24.08.0
    magick        : 7.1.1-41
    fzf           : 0.57.0
    fd/fdfind     : 10.1.0 / No such file or directory (os error 2)
    rg            : 14.1.1
    chafa         : 1.14.5
    zoxide        : 0.9.4
    7z/7zz        : 16.02 / No such file or directory (os error 2)
    jq            : 1.7.1

Clipboard
    wl-copy/paste: 2.2.1 / 2.2.1
    xclip        : No such file or directory (os error 2)
    xsel         : 1.2.1
```

### Describe the bug

Those jumps in previous tmux windows is made by yazi, then i manually return to window where i start yazi. If there is no previous window, tmux will throw notification about this
[Screencast_20241227_163110.webm](https://github.com/user-attachments/assets/f5ae57ce-2c6c-4270-8464-7ad3472e558c)

### Minimal reproducer
```sh
# tmux.conf
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

bind -n "M-[" previous-window
bind -n "M-]" next-window
```

### Checklist

- [X] I tried the [latest nightly build](https://yazi-rs.github.io/docs/installation#official-binaries), and the issue is still reproducible
- [X] I updated the debug information (`yazi --debug`) input box to the nightly that I tried
- [X] I can reproduce it after disabling all custom configs/plugins (`mv ~/.config/yazi ~/.config/yazi-backup`)

**Comment by sxyazi** [comment]
Duplicate of https://github.com/sxyazi/yazi/issues/2050, please read through that issue.

It happens because `tmux` sends the terminal response to Yazi to the wrong window (another window where the shell running instead of Yazi, in your case). 

I don't think there's a way to solve this within Yazi, as it's caused by `tmux` itself - `tmux` can interfere with Yazi's communication with the actual terminal in various ways.
 
So this needs `tmux` to provide a way to forward the terminal response for Yazi only to the active window (the one where Yazi is), not to another inactive window.

**Comment by dangooddd** [comment]
So currently there is no workaround for this? This does not happens if i remove bind -n and replace then with just bind

**Comment by sxyazi** [comment]
The only workaround I can think of is adding Alacritty to Yazi's image support database and, after detecting Alacritty through an environment variable (`$ALACRITTY_WINDOW_ID`), stopping the CSI-based terminal detection early to avoid any interference from `tmux` with Yazi and the actual terminal

However, the issue with this approach is that users of the Sixel fork of Alacritty would be affected, because the fork shares the same environment variable as Alacritty. This would cause Yazi to identify it as the original Alacritty and stop subsequent Sixel support detection

This is at most a "do-your-best" workaround. The issue will reappear when you use `tmux` over SSH because environment variables can't be synced through SSH. Unfortunately, there's very little Yazi can do about this

**Comment by sxyazi** [comment]
OK I added it in https://github.com/sxyazi/yazi/pull/2107, please try it out.

If users of the Sixel fork of Alacritty are affected later, then we can look for other solutions. Maybe add a separate environment variable in that fork, different from Alacritty's, to allow Yazi to recognize it as another Sixel-supported terminal rather than the original Alacritty.
