### ISSUE TITLE
Crates.io

### ISSUE THREAD

**Issue by jkenda** [sxyazi/yazi#222]
Please upload Yazi to crates.io so it can be installed and updated through Cargo.
It removes the need to clone the repository and build, you can just `cargo install yazi`

**Comment by sxyazi** [comment]
A dup of https://github.com/sxyazi/yazi/issues/179, closing this in favor of that.

BTW seems that Cargo also needs building by the users themself, but instead of fetching the source from GitHub, it's from crate.io.  It should work in the same way as:

```bash
cargo install --git https://github.com/sxyazi/yazi.git
```

Hmm not quite sure, please correct me if I'm wrong.

**Comment by jkenda** [comment]
I built from source before because I didn't even know Cargo had the ability to fetch from Git.

The whole reason I filed this issue is because I wanted Yazi to update along with all the other packages installed though Cargo. Now that I used Cargo to fetch from Git, Yazi iz listed when I run `cargo install-update -ag`. Thank you for your help and for making an awesome utility.
