### ISSUE TITLE
Archive preview with 7zip

### ISSUE THREAD

**Issue by ndtoan96** [sxyazi/yazi#225]
As you may know, Windows does not have `unar` and I'm not sure whether it is even installable. Thus, I plan to implement a preview with 7zip. Since 7zip is cross-platform, I'm not sure should I implement it as a Windows thing or as a fallback for `unar`. What do you think?

**Comment by sxyazi** [comment]
Windows can use `unar`, which can be downloaded directly or installed via `scoop install unar`.

But the version is somewhat outdated and lacks the "jss" parameter. See  https://github.com/sxyazi/yazi/issues/202#issuecomment-1735061193

**Comment by ndtoan96** [comment]
Using 7zip on Windows is the most sensible choice in my opinion since nowadays, people use it to replace Winrar. The `tag.gz` thing can be handled as special case.

One more thing, I see that you collect a lot of information aside from file name using `lsar`. Do you plan to use them in the future?

**Comment by sxyazi** [comment]
I plan to implement the archive as a directory in the future and make various file operations possible, so I have gathered this information.

I'm not sure if `7zip` can get this information and decompress individual files from the archive. Anyway, whether it's `unar` or `7zip`, I prefer to use just one (de)compression tool so that it's more convenient for adaptation and ensures consistent behavior.

**Comment by sxyazi** [comment]
Closing as 7zip does not provide a universal output format, such as XML or JSON.
