### ISSUE TITLE
remove operation don't complete

### ISSUE THREAD

**Issue by oluceps** [sxyazi/yazi#246]
## Summary
According to the upstream issue https://github.com/Byron/trash-rs/issues/57

In my case, removing file(s) from the top-level of `$HOME` to trash will get the schedule progress bar not moving on, and the operation not be successful as well. Caused by `$HOME` and trash bin not being in the same device.

This scenario is common in users who use `tmpfs` as root or bind mount their `~/.local` to other devices.

```
# ~/.local/state/yazi/yazi.log

  2023-10-04T20:46:40.372878Z  INFO core::tasks::scheduler: Failed to work on task Trash(FileOpTrash { id: 5, target: "/home/elen/b", length: 0 }): Error during a `trash` operation: FileSystem { path: "/home/elen/.local/share/Trash/files/b.3", kind: CrossesDevices }
    at core/src/tasks/scheduler.rs:79
```

https://github.com/sxyazi/yazi/blob/4527044547af74802450efc4dad85dc0be2b40b7/core/src/tasks/workers/file.rs#L181-L183
This will block the progress bar.

System: Linux 6.5.5

**Comment by sxyazi** [comment]
What's your expected behavior?

**Comment by oluceps** [comment]
> What's your expected behavior?

Expect move file into trash.

**Comment by oluceps** [comment]
> > What's your expected behavior?
> 
> Expect move file into trash. 

Or give some hints about what happened on the interface, the progress bar is just stuck there when removing files. Even though the log recorded errors.

**Comment by sxyazi** [comment]
I'm not sure how to fix it. Seems we can only wait for an upstream fix.

To my knowledge, for cross-device trashing, macOS creates a `.Trash` directory at the root of the device and simply moves files into it, while Windows permanently deletes files. I haven't observed the behavior on Linux yet. Is it more reasonable to keep the files on the current device or permanently delete them, rather than moving them to another device?

Regarding the UI, it's already included in the [theme system](https://github.com/sxyazi/yazi/pull/161). When a task fails, the progress bar changes color to red to alert the user.

**Comment by bassamsdata** [comment]
@sxyazi Thank you so much for the amazing work on this lovely file manager. It's really amazing file manager, and I use it daily but I noticed the below:

Since this is an open issue, I'd like to mention a similar bug:

### Deletion with `d`
when **deleting** a file (or multiple files) with `d` it shows `0% 1 left` even-though the file/files has been deleted and I emptied  the trash bin.  and even If I want to close yazi, it request me if I want to apport the process which of deletion, which  already the files are deleted.
> Note: this behaviour doesn't happen with `D`.

see below 2 screen shots. 
**here the statusline**
<img width="238" alt="Screen Shot 2023-10-09 at 7 45 37 PM" src="https://github.com/sxyazi/yazi/assets/105807570/93b181e4-133e-4dc2-9ed5-9fefec94ba41">
**and here the task window and trash bin folder**
<img width="1136" alt="Screen Shot 2023-10-09 at 7 46 08 PM" src="https://github.com/sxyazi/yazi/assets/105807570/45d3f80e-6358-451a-a398-7c6b6a2b78f3">

### Case sensitivity in searching help
one small request please, if you can remove the letter case sensitivity when searching in help.


### sessions or kind of persistant tabs
Are you planning on adding sessions or can I peresist specific tabs to be always  there when I open yazi.
example: "if we can save session with 3 tabs and each tab in specific dir"
or "open yazi with 2 tabs, one of them is always in specific dir"

## System info:
Terminal: kitty, xterm-kitty (and Alacritty)
MacOS 12.6
yazi 0.1.4

**Comment by sxyazi** [comment]
Hi @bassamsdata 

> Deletion with d

Could you please paste the error logs here by pressing `Enter` in the trash task to "inspect" it?

BTW, a similar issue was fixed yesterday. Could you give the latest main branch a try to see if it works for you?

> Case sensitivity in searching help

This should not be difficult to implement. Would you like to file an issue for it?

> sessions or kind of persistant tabs

Nice to have, would you like to implement it as a plugin once the plugin system is available?

**Comment by sxyazi** [comment]
@bassamsdata 

> there is no error, just empty page of the terminal with flickery cursor, then I press q to close it that it. the delete heppened but the progress in the statusline persisted.

> I did brew install yazi --HEAD but it says this is up to date. then reinstall it but I noticed that I built the same version that I had before 0.1.4. but yay the issue has been solved.

Has this issue been resolved in the latest main branch for you?

> I agree I think this should be as plugin. I'm sure someone would do it, unfortunately, I am not a rust programmer :(

No need for rust, just some lua :)

> One more question, are you planning to do undo for an action, like undo last deletion

I'm not quite sure how to implement it. Yazi is using [`trash-rs`](https://crates.io/crates/trash), but it only provides a [delete API](https://docs.rs/trash/3.1.0/trash/fn.delete.html), and not a restore one...

**Comment by bassamsdata** [comment]
Hey @sxyazi 

> Has this issue been resolved in the latest main branch for you?

Yes, it has been solved. Thanks 🙏

> No need for rust, just some lua :)

This is would be amazing, I love lua :). people would create a lot of plugins with lua :)

> I'm not quite sure how to implement it. Yazi is using [trash-rs](https://crates.io/crates/trash), but it only provides a [delete API](https://docs.rs/trash/3.1.0/trash/fn.delete.html), and not a restore one...

I was thinking of different solution like persistant folder on the corner of `yazi ui` for `trash bin` folder, but I don't think this is a good idea.
so yea, then no need to undo delete :)

**Comment by sxyazi** [comment]
Possibly related to your issue, https://github.com/sxyazi/yazi/issues/512
