### ISSUE TITLE
Search result is lost after going back to it

### ISSUE THREAD

**Issue by ndtoan96** [sxyazi/yazi#248]
Step to reproduce:
1. Search something with `s`
2. Use `h` to go to parent of a file
3. Use `H` to go back to the search result -> It's empty

I haven't look into the search functionality yet, but I think we can either store the search result or perform the search again.

**Comment by sxyazi** [comment]
I think that search results should not be added to the `backstack` since they are not actual directories but virtual ones.

When a user returns to the parent directory (or enters a subdirectory from the search results), it should be considered as abandoning those results, and the user should perform a new search when they need them.

**Comment by ndtoan96** [comment]
In that case, I think pressing `H` should returns to the path before the search. Because it feels weird to return to the search path without any result.
