### ISSUE TITLE
install: cannot stat './config/completions/yazi.bash': No such file or directory

### ISSUE THREAD

**Issue by magnetophon** [sxyazi/yazi#303]
When I try to ``nix run`` the latest master, https://github.com/sxyazi/yazi/commit/6d3457dde0234d677a1913cc6800a5f71a9d98da, I get: 
```console
 running 0 tests

 test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

 Finished cargoCheckHook
 checkPhase completed in 1 minutes 23 seconds
 installing
 Executing cargoInstallHook
 install: cannot stat './config/completions/yazi.bash': No such file or directory
 /nix/store/3pfjacvdg9f491lfqc9qb2d0nknx73fb-stdenv-linux/setup: line 144: pop_var_context: head of shell_variables not a function context
```
@XYenon

**Comment by sxyazi** [comment]
Sorry, I broke this at https://github.com/sxyazi/yazi/pull/298. Yazi needs to change its project structure in order to be published on crates.io.

I have [created a PR](https://github.com/sxyazi/yazi/pull/306) to fix the path; please give it a try to see if it works.

I also added a `YAZI_GEN_COMPLETIONS` environment variable, since when publishing the source directory cannot be changed. It may be needed as well, but I'm not sure where to add it.

https://github.com/sxyazi/yazi/blob/6d3457dde0234d677a1913cc6800a5f71a9d98da/yazi-config/build.rs#L10-L12
