### ISSUE TITLE
Escalate privileges if needed

### ISSUE THREAD

**Issue by alvaro17f** [sxyazi/yazi#307]
Let's say I want to copy a file owned by a user into root's folder.
Wouldn't it be great to  be asked for a password for that operation?

Thank you.

**Comment by sxyazi** [comment]
I'm not sure how to elevate privileges for a running process

**Comment by alvaro17f** [comment]
I think there's a crate called sudo, with a method named escalate_if_needed, but I'm not sure if this can help.

**Comment by sxyazi** [comment]
I've looked at its source code, and it simply calls sudo to start a new process and then exits the current process. These operations need to be done at startup, meaning Yazi must always run as root, rather than truly "on-demand", which is unacceptable in many cases where root privileges are not available.

https://gitlab.com/dns2utf8/sudo.rs/-/blob/main/src/lib.rs?ref_type=heads

**Comment by alvaro17f** [comment]
You're right

**Comment by sxyazi** [comment]
Closing as not possible
