### ISSUE TITLE
Cutting and pasting file to same folder modifies name unnecessarily

### ISSUE THREAD

**Issue by nimr0d** [sxyazi/yazi#330]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

Kitty

### Yazi version

yazi 0.1.5

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

Cutting a file or set of files into their current folder adds a "_1" to their filename.

### Expected Behavior

Pasting should go through without modifying the file name, and the "cut" file should no longer be considered cut.

### To Reproduce

Have the selection over any file and type "xp".

### Anything else?

I attempted a fix in yazi-core/src/tasks/workers/tasks.rs by changing
`if force && u == &to`

to 

`if u == &to`

in the function "file_cut". This did not solve the problem because the file stayed in "cut" mode after pasting.

**Comment by sxyazi** [comment]
In the case of "copy", this is the expected behavior and is useful when you need to create a copy of a file.

As for "cut", in this scenario, it may seem can ignore the user's keypress, but I tend to keep this behavior as well. This ensures consistency between the "copy" and "cut" actions, and sometimes it can also be useful: For example, if I want to rename `yazi.toml` to `yazi_1.toml` to test Yazi's default configuration without user settings, it's a simple way to do so.

If you're concerned about forgetting the current mode ("cut" or "copy") and pressing "p" by mistake, this issue will address it: https://github.com/sxyazi/yazi/issues/319. At that point, "p" will be removed, and only "x" and "y" will be retained.
