### ISSUE TITLE
Previews in Zellij

### ISSUE THREAD

**Issue by Squirreljetpack** [sxyazi/yazi#334]
### What system are you running Yazi on?

macOS

### What terminal are you running Yazi in?

Alacritty

### Yazi version

yazi 0.1.5

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

Zellij and yazi together seem to have problems displaying sixel images
I tested on Linux and mac
On linux Zellij+alacritty+yazi shows no image.
On any sixel supportiing terminal like wezterm or iterm, yazi generally works fine on its own but glitches when run with zellij.
for example, with yazi on iTerm, the previews work fine, but if I run yazi through zellij the previews get corrupted.
(I also tried using alacritty-sixel, by setting $TERM_PROGRAM to foot, again the previews get corrupted)

I also tried:
Straight up Alacritty and yazi: Yazi defaults to using Chafa just fine (is there a way to configure preview quality?)
Alacritty and yazi + Zellij: no image is displayed (would like to at least have chafa work).

When launching alacritty->zellij->Yazi from Apple Terminal
I got this stdout
POSSIBLE ISSUE: unit 2 GLD_TEXTURE_INDEX_2D is unloadable and bound to sampler type (Float) - using zero texture because texture unloadable.

### Expected Behavior

Images display properly
Maybe some way to manually override how images are displayed? (Choose whether previews are in Chafa, sixel or none)

### To Reproduce

Described above, let me know if neef more details.

### Configuration

Default configs

**Comment by sxyazi** [comment]
# Issue 1

> On any sixel supportiing terminal like wezterm or iterm, yazi generally works fine on its own but glitches when run with zellij.
> for example, with yazi on iTerm, the previews work fine, but if I run yazi through zellij the previews get corrupted.
> (I also tried using alacritty-sixel, by setting $TERM_PROGRAM to foot, again the previews get corrupted)

I think this is an issue with Zellij itself, not Yazi. See https://github.com/zellij-org/zellij/issues/2576

Quote from https://github.com/sxyazi/yazi/pull/181#issuecomment-1744307719:

During the last test, there are some issues with the graphics support for Zellij. It occasionally glitches, and likely an issue with Zellij itself, since tmux works fine with the same protocol.

# Issue 2

> On linux Zellij+alacritty+yazi shows no image.
> Straight up Alacritty and yazi: Yazi defaults to using Chafa just fine (is there a way to configure preview quality?)
Alacritty and yazi + Zellij: no image is displayed (would like to at least have chafa work).

As for falling back to Chafa, it's nice to have, but I'm not familiar with Zellij, I'd like to know if there's any way to detect the current terminal's `$TERM`, `$TERM_PROGRAM`, and `$XDG_SESSION_TYPE` values within Zellij, similar to what's done in tmux: https://github.com/sxyazi/yazi/blob/73941c22917469bdd7877877f80981438af653fd/yazi-adaptor/src/adaptor.rs#L83

Regarding configuring preview quality, Yazi offers Chafa support through Überzug++. AFAIK, Überzug++ does not provide any parameters for configuring quality. Here is its parameter list: https://github.com/jstkdng/ueberzugpp#usage

# Issue 3

> When launching alacritty->zellij->Yazi from Apple Terminal
> I got this stdout
> POSSIBLE ISSUE: unit 2 GLD_TEXTURE_INDEX_2D is unloadable and bound to sampler type (Float) - using zero texture because texture unloadable.

I suspect this is an issue with Überzug++, since Yazi doesn't use any GLD interfaces, could you try uninstalling Überzug++ and then running Yazi again to see if the problem still exists?

**Comment by Squirreljetpack** [comment]
1. ah that seems right.
2. I think you can do for zellij what you're doing for tmux more directly. tmux changes the TERM_PROGRAM environment variable but zellij doesn't.
So if you remove the check for zellij-session (first line), the adaptor will be set based on the underlying $TERM, $TERM_PROGRAM.
Checking for Zellij session name looks a bit out of place since whether sixel works depends on the terminal and zellij, although I saw that zellij plans to have fall backs for sixel themselves so setting type as sixel always might make sense.
For now though, after some testing it seems Zellij sixel support is not great, even img2sixel doesn't work.
About Chafa, i see, the resolution can only be modified on user end by changing font size of terminal.
3. Uninstalling Überzug++ fixes it and also removes the images :). It was just a log i saw, I don't know rust yet so I thought it might be helpful.

Additional thoughts:
4. I think i found a bug in the code for ueberzug. Instead of just rect.x, it should be

`			let s = format!(
				r#"{{"action":"add","identifier":"yazi","x":{},"y":{},"max_width":{},"max_height":{},"path":"{}"}}{}"#,
				rect.x-rect.width,
				rect.y,
				rect.width,
				rect.height,
				path.to_string_lossy(),
				"\n"
			);`
Testing on different terminals shows it works.
5. How do you get debug messages? Like debug!("ueberzug rect after adjustment: {:?}", rect); In yazi.log i only found errors.
6.  Ueberzg X11 works for me but only for a short period after that the images stop showing up. I've modified yazi on my end to always use Chafa if specified (It has been the only stable one throughout). Given how unstable a lot of these protocols are, it might be a good idea to let users configure which one they want.

**Comment by sxyazi** [comment]
> I think you can do for zellij what you're doing for tmux more directly. tmux changes the TERM_PROGRAM environment variable but zellij doesn't.

Nice, I'll create a PR to support it.

> Uninstalling Überzug++ fixes it and also removes the images :). It was just a log i saw, I don't know rust yet so I thought it might be helpful.

Yazi starts Überzug++ as a subprocess and shares stdout with it, so the error should be output by Überzug++. You can try to use it directly without Yazi as per https://github.com/sxyazi/yazi/issues/134#issuecomment-1714397167 to see if the issue still exists.

> I think i found a bug in the code for ueberzug. Instead of just rect.x, it should be

I didn't understand your meaning. Could you take a screenshot?

> How do you get debug messages? Like debug!("ueberzug rect after adjustment: {:?}", rect); In yazi.log i only found errors

You need to run Yazi in debug mode, i.e. `cargo build` rather than `cargo build --release`, https://yazi-rs.github.io/docs/installation#build-from-source

> Ueberzg X11 works for me but only for a short period after that the images stop showing up. I've modified yazi on my end to always use Chafa if specified (It has been the only stable one throughout). Given how unstable a lot of these protocols are, it might be a good idea to let users configure which one they want.

If Yazi has a possibility of handling it correctly, I prefer to let Yazi do it for the user, as this involves a lot of complexity (Quote from https://github.com/sxyazi/yazi/issues/311#issuecomment-1776345037): 

Some terminals support all Kitty, Sixel, and iTerm2 protocols, while others only support one of them. When users run Yazi in tmux, only Sixel and iTerm are available; when users run in Zellij, only Sixel is available; when users are on Windows, WezTerm and Mintty can only use iTerm2; if the user's terminal doesn't support any of these, then Ueberzug is needed. The combination of these conditions will make things get complicated, so it's up to Yazi to choose the best way for the user

**Comment by sxyazi** [comment]
Hi I made a PR for that, https://github.com/sxyazi/yazi/pull/336, let me know if it works for you!

**Comment by Squirreljetpack** [comment]
Sure that looks like it would work to get the proper variables for Zellij.
It doesn't change anything for me however because my problems are from using Zellij, which doesn't display Sixels even if underlying terminal supports them (for now). If I use a terminal that doesn't support sixels then yazi uses ueberzug which i found a lot of problems with as well (stops displaying images, bad image dimensions etc.). For now I'm still using a modified version that'll just use Chafa (which due to being supplied by Ueberzug still has bad dimensions i.e. too small).

**Comment by sxyazi** [comment]
Sadly Zellij's support for images is still lacking, and I believe the best current solution is not to run Yazi within Zellij.

As for the issue of Chafa not displaying images and the problem with images being too small, I wonder if it's an issue with Yazi itself or a bug in Ueberzug. Could you please check if the problem still exists by following https://github.com/sxyazi/yazi/issues/134#issuecomment-1714397167? I'd like to know what Yazi can do to address this.

**Comment by Squirreljetpack** [comment]
echo '{"action":"add","identifier":"preview","max_height":0,"max_width":0,"path":"layer.png","x":0,"y":0}' | ueberzug layer

(process:64370): VIPS-WARNING **: 16:04:03.898: unable to load "/usr/lib/vips-modules-8.14/vips-openslide.so" -- libopenslide.so.0: cannot open shared object file: No such file or directory
memory: high-water mark 0 bytes

**Comment by sxyazi** [comment]
What happens after doing this? Is the image displayed in the correct position and with the correct size?
