### ISSUE TITLE
Support for more editing commands in input box

### ISSUE THREAD

**Issue by Tweoss** [sxyazi/yazi#343]
### Is your feature request related to a problem? Please describe

I frequently use the jump to start or end of line, clear to start, and forward delete in the terminal. It would be great if these worked in addition to the vim keybindings. 

### Will you be willing to contribute this feature?

- [x] Yes, I will try to implement it

### Describe the solution you'd like

I would like to be able to use `ctrl+a` to jump to the start of the line, `ctrl+e` to the end, `ctrl+d` to delete a single character (to the right of the cursor), `alt+backspace` to delete a word, and `alt+d` to delete a word to the right of the cursor. 

### Additional context

It looks to me that there is already support for handling `modifier+key` via crossterm in the input handling code. Additionally, it seems like most of the desired functionality is already implemented, and the rest of the functionality would be similar to what is already there. 

If this sounds like it would be useful to others as well and would not contribute to much to the complexity of the codebase, I can try to take a crack at it.

**Comment by sxyazi** [comment]
Nice to have! This is a feature I've been wanting to add for a while, but I haven't had the time to complete it. I'm glad to see that you're willing to implement it! ❤️️

I've left a place for implementing it in the `type_()` function: https://github.com/sxyazi/yazi/blob/1f744810f4c4ef935e28c09f7b378f666e274ace/yazi-core/src/input/input.rs#L205-L208

You can add the `ctrl+a` and `ctrl+e`, etc. keys to this match block, it should work.

**Comment by Tweoss** [comment]
@sxyazi  I can't quite tell how to handle deleting words. The functionality evidently exists, with `dw` and `db`, but I can't tell where it is implemented. Would appreciate some pointers to implement `alt+backspace` and `alt+d` in insert mode. 

I also added a flag for the backspace method to be `forward_delete` or normal delete. I'm not sure if this is the style you like, so feel free to change it or let me know what you'd prefer.

**Comment by sxyazi** [comment]
This is amazingly fast! Thanks for your work!

Currently, there is no separate function for deleting a single word. `dw` and `db` are combinations of [`delete`](https://github.com/sxyazi/yazi/blob/1f744810f4c4ef935e28c09f7b378f666e274ace/yazi-core/src/input/input.rs#L237) + [`forward`](https://github.com/sxyazi/yazi/blob/1f744810f4c4ef935e28c09f7b378f666e274ace/yazi-core/src/input/input.rs#L169) and [`delete`](https://github.com/sxyazi/yazi/blob/1f744810f4c4ef935e28c09f7b378f666e274ace/yazi-core/src/input/input.rs#L237) + [`backward`](https://github.com/sxyazi/yazi/blob/1f744810f4c4ef935e28c09f7b378f666e274ace/yazi-core/src/input/input.rs#L146) since Vi divides a single operation into two steps, and the actual deletion occurs in the [`handle_op`](https://github.com/sxyazi/yazi/blob/1f744810f4c4ef935e28c09f7b378f666e274ace/yazi-core/src/input/input.rs#L291) function, which is triggered when the user presses the final `w` or `b`.

The entire process involves Vi state transitions. Maybe we can extract some key code from it and create a separate function:

1. Finding word boundaries:
    https://github.com/sxyazi/yazi/blob/1f744810f4c4ef935e28c09f7b378f666e274ace/yazi-core/src/input/input.rs#L152-L165

2. Performing the deletion:
    https://github.com/sxyazi/yazi/blob/1f744810f4c4ef935e28c09f7b378f666e274ace/yazi-core/src/input/input.rs#L300-L303

As for the `backspace`, it looks good to me!

**Comment by Tweoss** [comment]
Sounds good, thanks for the pointers! I'll make an attempt on refactoring as soon as I can, depending on homework intensity 😛.

**Comment by musjj** [comment]
Can't we integrate the [reedline](https://github.com/nushell/reedline) library instead? It's the library that nushell uses. It already supports both Emacs and vi bindings with more advanced stuff coming (like visual selection).

**Comment by sxyazi** [comment]
@musjj  `reedline` crate still lacks some key features at present, such as visual selection and the ability to break down operations into individual commands and combine them

**Comment by sxyazi** [comment]
Sure! I'll do that asap
