### ISSUE TITLE
Some results are not colorized when searching

### ISSUE THREAD

**Issue by Hanaasagi** [sxyazi/yazi#348]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

alacritty 0.12.3 (5efb0690)

### Yazi version

yazi 0.1.5

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

https://github.com/sxyazi/yazi/assets/9482395/81948f8f-e94c-4c36-884a-f21d3a58c5f8

As shown in the video, when search results cause the current page to scroll, this part is not rendered in color. It's white, not blue. When I scroll down, the color is rendered.

### Expected Behavior

All results is colorized.

### To Reproduce

Use a search that can match many results.

### Configuration

no config.

**Comment by sxyazi** [comment]
Thanks for the reporting.

This is a known bug, and it has been noted in the bug section of [Feature requests](https://github.com/sxyazi/yazi/issues/51) as "Precache n+1 pages of mimetype instead of n for the better experience".

It occurs when the user's cursor is at the file boundary between pages `n` and `n+1`, and it is unrelated to search. I think adding some like `emit!(Pages(new+1))` below `emit!(Pages(new))` can fix it:

https://github.com/sxyazi/yazi/blob/1f744810f4c4ef935e28c09f7b378f666e274ace/yazi-core/src/tab/folder.rs#L60

Would you like to create a PR for this? Which would be greatly appreciated!

**Comment by Hanaasagi** [comment]
Emm, `emit!(Pages(new+1))` is not fixed this.

https://github.com/sxyazi/yazi/blob/1f744810f4c4ef935e28c09f7b378f666e274ace/yazi-fm/src/app.rs#L145-L150

When processing the events, it checks if the `manager.current().page == page`. However, even if this 'if' statement is removed, it still doesn't work as it relies on `current().paginate()`, which depends on the `page` variable.

https://github.com/sxyazi/yazi/blob/1f744810f4c4ef935e28c09f7b378f666e274ace/yazi-core/src/tab/folder.rs#L118-L125

But I think this is very close, and I'm working on fixing this.
