### ISSUE TITLE
Support ignore files

### ISSUE THREAD

**Issue by musjj** [sxyazi/yazi#350]
### Is your feature request related to a problem? Please describe

It'd be nice to be able to automatically hide files in ignore files

### Will you be willing to contribute this feature?

- [ ] Yes, I will try to implement it

### Describe the solution you'd like

Support ignore files. There's this snippet from `man fd` describing the types of ignore files that might be useful to support:

```
-I, --no-ignore
       Show search results from files and directories that would otherwise be ignored by

       • .gitignore

       • .git/info/exclude

       • The global gitignore configuration (by default $HOME/.config/git/ignore)

       • .ignore

       • .fdignore

       • The global fd ignore file (usually $HOME/.config/fd/ignore )

       The flag can be overridden with '--ignore'.
```

I think supporting at least `.gitignore` and `.ignore` would be reasonable.

**Comment by musjj** [comment]
Is it really *that* inefficient? It only needs to check and parse ignore files in the 2-3 visible panes right? fd does this and it's still the most efficient file list tool all around.

**Comment by sxyazi** [comment]
> Is it really _that_ inefficient? It only needs to check and parse ignore files in the 2-3 visible panes right? fd does this and it's still the most efficient file list tool all around.

Due to the necessity of recursively collecting all `.gitignore` files before actually loading the file list, this will become the sole synchronous blocking factor for Yazi at present, especially for slower devices or network storage.

Introducing additional caching mechanisms is also required for this, necessitating an appropriate cache invalidation strategy. 

Maybe we could collect `.gitignore` while loading the file list and apply these filters to the list once it's gathered, but this would make it more complex and result in list flickering.



> I see ranger using a global regex to filter them. e.g.
> 
> ```
> # Which files should be hidden? (regular expression)
> set hidden_filter ^\.|\.(?:pyc|pyo|bak|swp)$|^lost\+found$|^__(py)?cache__$
> ```

Yea that would be an ideal approach, we could expand it further though

**Comment by Linus789** [comment]
> > I see ranger using a global regex to filter them. e.g.
> > ```
> > # Which files should be hidden? (regular expression)
> > set hidden_filter ^\.|\.(?:pyc|pyo|bak|swp)$|^lost\+found$|^__(py)?cache__$
> > ```
> 
> Yea that would be an ideal approach, we could expand it further though

Besides global filtering, I think it would be nice to have a way to hide files in specific directories, too. For example, Nautilus, Dolphin and Thunar use the `.hidden` file (https://fosspost.org/hide-files-folders-linux/) which only needs to be read for the current folder. If this would be the correct design choice for yazi however, I don't know.

**Comment by sxyazi** [comment]
This FR is already been in [Feature Requests](https://github.com/sxyazi/yazi/issues/51), closing in favor of that list
