### ISSUE TITLE
OPUS image preview

### ISSUE THREAD

**Issue by hakan-demirli** [sxyazi/yazi#396]
### Is your feature request related to a problem? Please describe

no.

### Will you be willing to contribute this feature?

- [ ] Yes, I will try to implement it

### Describe the solution you'd like

I use the following code in lf file manager to display opus previews. I use lf as a music player together with `mpv`. I wish to achieve the same with yazi.
```bash
*.opus)
	thumbnail="$TEMPDIR/thumbnail.png"
	ffmpeg -y -i "$file" -vframes 1 "$thumbnail"
    preview "$thumbnail"
	;;
```
FFMPEG is cross-platorm and just works everywhere but I am not sure if there is another way without adding a dependency.

### Describe alternatives you've considered

As an alternative lf file manager user config allows custom previewers. Maybe this feature can also be a plugin but since preview is embedded into yazi I think it should be part of the core.

### Additional context

![image](https://github.com/sxyazi/yazi/assets/78746991/0bef8400-1784-4585-a7d8-162be94d3d11)

**Comment by sxyazi** [comment]
`opus` is an audio format, not an image, hence it's not possible to include it as part of the Yazi image decoding functionality, since the [image crate](https://crates.io/crates/image) doesn't support it. It will eventually be implemented as a custom previewer by the user.

Closing this issue in favor of https://github.com/sxyazi/yazi/issues/182
