### ISSUE TITLE
Bulk rename: Allow VSCode as EDITOR

### ISSUE THREAD

**Issue by abd-liac** [sxyazi/yazi#399]
### Is your feature request related to a problem? Please describe

The default `EDITOR` nano is weak in functionality, but when I switch to VSCode, the bulk file is always **blank**.

### Will you be willing to contribute this feature?

- [ ] Yes, I will try to implement it

### Describe the solution you'd like

Make VSCode open bulk file correctly.

**Comment by sxyazi** [comment]
This is because the `code` command exits immediately after execution, without waiting for the user to actually finish editing the file, thus not blocking the current terminal. This makes Yazi think that the user has completed editing - because `code` indeed exits.

I'm not a VSCode user, is there any way to make `code` block the terminal until the user finishes editing and exits VSCode?

**Comment by abd-liac** [comment]
It seems [`--wait`](https://code.visualstudio.com/docs/editor/command-line?ref=dave-brock#_core-cli-options) can deal with it. I'll give it a try back home, thanks for troubleshooting.

**Comment by sxyazi** [comment]
Yea you're right, just tested it works for me:

```rust
{ run = 'code -w "$@"', block = true },
```


https://github.com/sxyazi/yazi/assets/17523360/73211c88-b89f-4edf-a7f6-cb43a7df20df

Doc of `[opener]`: https://yazi-rs.github.io/docs/configuration/yazi#opener
