### ISSUE TITLE
Colored Icons

### ISSUE THREAD

**Issue by dlvhdr** [sxyazi/yazi#402]
### Is your feature request related to a problem? Please describe

I would like to have the ability to show colored icons, based on filetype.

### Will you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Consider something similar to nvim-tree in neovim
![image](https://github.com/sxyazi/yazi/assets/6196971/1ebd1dc4-b30c-4d17-b551-d658ed596c40)

### Describe alternatives you've considered

Changing colors based on filetype but really I only want to change the color of the icons.

**Comment by sxyazi** [comment]
Does this mean that we need to set a text foreground color for each icon? Are there any ideas for extending this without disrupting the current icon configuration format?

https://github.com/sxyazi/yazi/blob/4d7d2ef082d4d52ef4cd77400853415b519137c8/yazi-config/preset/theme.toml#L171-L175

**Comment by dlvhdr** [comment]
Hmm we could do something similar to what starship.rs does:

```
[icons]

"Desktop/"     = "(fg=yellow)"
"Documents/"   = ""
"Downloads/"   = ""
```

**Comment by sxyazi** [comment]
Hi, I added a new `fg` property to the icon rule in https://github.com/sxyazi/yazi/pull/503 PR.

You can now set it like this:

```bash
	{ name = "*.c"    , text = "", fg = "your color" },
```

There's a list of all available colors: https://yazi-rs.github.io/docs/configuration/theme#types, hex color is also supported though.

BTW, in that PR, I also converted the icon rules into an ordered list to address https://github.com/sxyazi/yazi/issues/458.

**Comment by dlvhdr** [comment]
This is amazing, thank you!

**Comment by og900aero** [comment]
And what is syntax? Because I try 

```
[icons]

rules = [
	{ name = "*./", text = "", fg = "#00af87" }
]
```

But yazi doesnt start.

**Comment by musjj** [comment]
It'd be nice if yazi is shipped with default colors for the icons. Maybe we can take a look at https://github.com/nvim-tree/nvim-web-devicons for reference.

**Comment by sxyazi** [comment]
@og900aero 
Hi, this PR was merged 2 days ago, it currently needs the latest code from the main branch.

@musjj 
nvim-web-devicons has two different colors for each icon - dark and light. Since we cannot predict the theme color of the user's terminal, perhaps it can only be included in the corresponding dark/light theme of Yazi? I'm not sure how to address it to better match the user's terminal yet. Any thoughts?

**Comment by musjj** [comment]
@sxyazi 

Well, we can just settle with colors that works okay against both light and dark backgrounds (e.g. `nnn` hardcodes the icon colors without caring about light/dark).

But you can also parse the terminal background color via OSC 11 and guess if it's dark or light by calculating its luminance. This is what neovim does, here's the relevant code:

https://github.com/neovim/neovim/blob/3bcf8e5622f29a65564bf2f7672997432e183dfa/runtime/lua/vim/_defaults.lua#L222

This will then affect the default theme colors as seen here:

https://github.com/neovim/neovim/blob/3bcf8e5622f29a65564bf2f7672997432e183dfa/runtime/colors/vim.lua#L207

But this requires extra logic which have to be handled by either extending the config structure or handling it in code.

**Comment by sxyazi** [comment]
@og900aero
Ah just noticed it should be `[icon]` not `[icons]` since we move the icons into the `rules`. https://github.com/sxyazi/yazi/blob/c335b0272b48dd76a82fec5db4c47f6d89cd95fb/yazi-config/preset/theme.toml#L171-L173

@musjj 
Sounds good, maybe we can start by hardcoding these colors like `nnn`. Do you want to create a PR for it to add these colors?

**Comment by og900aero** [comment]
@sxyazi 
Thx, now working great.
