### ISSUE TITLE
"index out of bounds" crash when folder_offset is 0,0,0,0 selecting two files and moving cursor up

### ISSUE THREAD

**Issue by ThGrSoRu** [sxyazi/yazi#413]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

foot

### Yazi version

yazi 0.1.5 (d549831 2023-11-29)

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

`The application panicked (crashed).
  index out of bounds: the len is 23287 but the index is 23332
in /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.24.0/src/buffer.rs, line 210
thread: main`

Setting `folder_offset` to `[0,0,0,0]` and selecting 2 video files that are not separated by another file or folder and then moving the cursor up, crashes yazi.

### Expected Behavior

Yazi should not crash, because of a setting that is within it's valid parameters.

### To Reproduce

Set `folder_offset` to `[0,0,0,0]` and select 2 video files that are not separated by another file or folder and then move the cursor up.

### Configuration

[Custom UI file](https://github.com/sxyazi/yazi/files/13518416/ui.txt)

**Comment by sxyazi** [comment]
Thank you for the report.

This is an edge case where both the `top` and `bottom` of the `folder_offset` should be set to `1` unless you've removed the default "directory path row" above and the "status bar" below.

When they're still present and the value is set to `0`, Yazi retrieves files that are two lines taller than the list height — these two files will appear outside the list when you scroll to the bottom.

The crash here occurred because the "selection indicator" exceeds the visible area of the user's terminal. I've created a PR to fix it, and it shouldn't crash now, https://github.com/sxyazi/yazi/pull/416, let me know if it works for you.

However, you still need to specify a reasonable value for `folder_offset`, or else the indicator won't be visible, since it's outside the screen.

**Comment by ThGrSoRu** [comment]
Yes. This prevents the crash while allowing `folder_offset` to be `[0,0,0,0]`. Thank you!
