### ISSUE TITLE
image looks like pixel

### ISSUE THREAD

**Issue by zeekrs** [sxyazi/yazi#455]
### What system are you running Yazi on?

macOS

### What terminal are you running Yazi in?

alacritty 0.12.3

### Yazi version

yazi 0.1.5

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

i have installed ueberzagpp and set the tmux options
the image can be preview but looks like pixel 
i don't know something went wrong
![CleanShot 2023-12-26 at 16 42 59@2x](https://github.com/sxyazi/yazi/assets/87763555/eb22ff39-7a2d-4f2d-9f29-2ac4a5ac5eaa)

### Expected Behavior

the image preview well

### To Reproduce

the origin image is 
![child_river_dreams_3840x2400](https://github.com/sxyazi/yazi/assets/87763555/5e44c0a8-ee8a-46bd-a5b1-a83b9ce23e54)

### Configuration

only changed the keymap.toml

**Comment by sxyazi** [comment]
This is expected behavior:

- Your terminal is [not in the supported list](https://github.com/sxyazi/yazi?tab=readme-ov-file#image-preview) - Alacritty doesn't support displaying images itself
- And you're not in an X11/Wayland environment - which makes the X11/Wayland support of Überzug++ ineffective

So Yazi falls back to [Chafa](https://github.com/hpjansson/chafa) automatically, and this is how it looks. See https://github.com/sxyazi/yazi?tab=readme-ov-file#image-preview for more information.
