### ISSUE TITLE
Yazi rapidly generates cached images when browsing the cache directory (/tmp/yazi)

### ISSUE THREAD

**Issue by DarkKronicle** [sxyazi/yazi#481]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

Kitty v0.31.0

### Yazi version

yazi 0.1.5 (3fcc201 2024-01-05)

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

If you have any cached images in the cache directory (`/tmp/yazi` in my case), browsing that folder within yazi will continually generate more files.

### Expected Behavior

It would be optimal if yazi reused the cached files in the directory. If I understand the caching code correctly, it encodes the path in md5. If the current directory is the cache directory, you could just fetch the direct file by name, instead of re-encoding it.

### To Reproduce

1. Run `yazi --clear-cache`
2. Run `yazi`, preview at least one image
3. In yazi, navigate to `/tmp/yazi`, and enter it
4. See amount of files skyrocket.

**Comment by sxyazi** [comment]
Hi, I made a PR to fix it, https://github.com/sxyazi/yazi/pull/504. Let me know if it works for you!

**Comment by DarkKronicle** [comment]
This seems to break previews. It gets stuck on the task:
```
Run preloader `mime.lua` with 8 target(s)
```
 Where 8 changes to how ever many files in the directory (I think).

**Comment by DarkKronicle** [comment]
Oh wait this seems to be a problem with either the main branch or however I'm compiling it. Trying on the main branch it gets stuck on mime.lua as well

**Comment by sxyazi** [comment]
This is because some adjustments were made to the yazi.toml of the main branch recently before the v0.2.0 release - [removing the .lua extension](https://github.com/sxyazi/yazi/commit/085f7e39bf3bbca48e885ae5879b28c4070fb281)

And unfortunately you used the `yazi.toml` copied from the main branch earlier, so if you don't need to configure `preloaders` or `previewers`, just delete the entire `[plugin]` part from your `yazi.toml` and this should make it rework

**Comment by DarkKronicle** [comment]
Looks like it works!

**Comment by sxyazi** [comment]
Oh thank you for testing, let me merge it now!
