### ISSUE TITLE
Use native/desktop image viewer outside of terminal for image previewing

### ISSUE THREAD

**Issue by fritzrehde** [sxyazi/yazi#540]
### Is your feature request related to a problem? Please describe

I am using alacritty with tmux on wayland, so this already limits my choices regarding image previewers. I tried `ueberzugpp` (without tmux first), and the images are all cut off because they are too far on the right. So I'm looking for alternatives.

### Will you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

It seems cumbersome to need (complex) terminal image viewers, when I already have native image viewers installed on my system (e.g. `imv`). To me the most intuitive solution to preview images would be: I have my terminal open on a Linux window manager workspace. What I would like: when I hover over an image with the cursor, my configured image viewer (e.g. `imv`) is opened (due to my Linux window manager config it would be opened right of the terminal) and displays the currently selected window. Importantly, once I move the cursor down in `yazi`, I would need the desktop image viewer to dissappear/be killed. I acknowledge that this is quite a weird, hacky solution, but I prefer the flexibility of using native utilities that work over the somewhat hacky terminal image displayers. Therefore, my question is: Is the feature I describe already possible with yazi (I know it's not built-in, but can I hack it together somehow)? If not, what additions to yazi would be required to make it work. I guess this issue could also be broadened to: `Use native/desktop application outside of terminal for file type previewing`, but I wanted to keep it concise for now.
Thanks for creating such an awesome tool!

### Describe alternatives you've considered

`ueberzugpp`, but that didn't work, as described above (maybe that's a separate bug, but even if it gets fixed, I would still probably prefer to use the process I described).

**Comment by sxyazi** [comment]
I think it can currently be achieved through Yazi's plugin system. You just need to bind your up and down keys to your plugin and, when switching files up and down, use Lua to call your image viewer.

This is very similar to what [smart-enter](https://yazi-rs.github.io/docs/tips#smart-enter-enter-for-directory-open-for-file) does - you can use `cx` to get Yazi's application data when the key is pressed, including file list data and the data about the hovered file, see https://yazi-rs.github.io/docs/plugins/common#app-data

You can also use the [`mime()` function](https://yazi-rs.github.io/docs/plugins/common/#folderfile) to get the mime-type of the file for determining whether it's an image and handle it accordingly.

I won't natively support it, and `ueberzugpp` is currently the best choice, since it's a bit hacky and requires meeting the following conditions to work:

1. The user must be using a window manager and have configured the image viewer to always display on the left/right.
2. The user's installed image viewer must support opening images via parameters, and the parameters vary depending on the viewer and platform.
3. It's not possible to adapt to all viewers, so adapting to one (or a few) while leaving others without support is still a problem.
