### ISSUE TITLE
Recursive directory size not updating

### ISSUE THREAD

**Issue by fritzrehde** [sxyazi/yazi#544]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

alacritty 0.13.1 (fe2a3c56)

### Yazi version

yazi 0.1.5 (c3a8bdc 2024-01-09)

### Did you try the latest main branch to see if the problem has already been fixed?

Not tried, and I'll explain why below

### Describe the bug

I toggle between two sort modes using keybindings:
```toml
	{ on = [ "s" ], exec = [ "linemode size", "sort size --reverse" ],            desc = "Sort by size (reverse)" },
	{ on = [ "S" ], exec = [ "linemode none", "sort alphabetical --dir-first" ],  desc = "Sort alphabetically" },
```
When I'm in the `sort size --reverse` mode, and delete a large number of files (e.g. one directory was reduced from 25 GB to next to nothing), the linemode size numbers do not update (still says 25 GB for that particular directory). I am guessing this is somewhat by design, because these recursive directory size calculations are probably quite expensive. However, my current situation is not ideal, as I have found that only quitting and restarting yazi properly updates the values. Do I manually have to initiate a recalculation of recursive directory sizes? I feel like `yazi` could at least do this recalculation for directory `a` by itself if one or more of `a`s subdirectories are deleted from within yazi as well, right?

### Expected Behavior

Like I said, maybe I am already observing expected behaviour, but it would be nice for some sort of semi-automated updates to the recursive directory size calculations.

### To Reproduce

Quite obvious from above fields, I think.

**Comment by sxyazi** [comment]
For better performance, Yazi will only watch the CWD and its parent directory, along with the hovered file that's a directory, up to three levels. It does not recursively watch changes in all subdirectories, making it impractical.

Yazi cannot be aware of deeper changes in your directory, and additionally, there is a problem with this approach - when you are at "/", does it mean that changes in "/a/b/c/d/e/f" should also update the size of "/"? Otherwise, this feature is incomplete and works inconsistently.

Also, for rapidly changing files in a directory, such as writing to hundreds of files simultaneously, triggering a re-calculation of size continuously is an inefficient practice.

I am not sure what the optimal solution is, and I would like to know how other file managers handle this. Perhaps we can take inspiration from them.
