### ISSUE TITLE
Recursively deleting directories may hang due to permissions issues

### ISSUE THREAD

**Issue by codido** [sxyazi/yazi#574]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

foot

### Yazi version

yazi 0.2.2 (28870ad 2024-01-24)

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

Delete a directory with non-writable sub-directories containing data in it results in the deletion task hanging with the following errors:
```
Delete task failed: FileOpDelete { id: 3, target: /tmp/foo/bar/foobar, length: 0 }, Permission denied (os error 13)
Failed to work on this task: Permission denied (os error 13)
```

### Expected Behavior

Either warn about the failure and remove it from the active tasks or forcefully remove the directory.

### To Reproduce

1. Create a directory with a subdirectory in it: `mkdir -p /tmp/foo/bar`
2. Create a file inside the subdirectory: `touch /tmp/foo/bar/foobar`
3. Remove write permissions from the subdirectory: `chmod -w /tmp/foo/bar`
4. In yazi, try to permanently remove the directory (`/tmp/foo` in this case)  

### Configuration

no config

**Comment by sxyazi** [comment]
Thanks for the detailed reproduction steps.

This is the expected behavior. When deletion fails, Yazi will keep the task in the list to notify the user that the task was not completed. You can press `x` to remove the task from the list.


https://github.com/sxyazi/yazi/assets/17523360/866637de-7c04-4a96-b93d-ba7b1e240dc3
