### ISSUE TITLE
Cannot open file/folder on windows 10

### ISSUE THREAD

**Issue by RomaLzhih** [sxyazi/yazi#699]
### What system are you running Yazi on?

Windows

### What terminal are you running Yazi in?

Wezterm & Windows Terminal

### Yazi version

yazi 0.2.3

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

Cannot use `<ENTER>`/`<C-ENTER>`/`o`/`O` to open a file/folder. There is no response when press these buttons. 

### Expected Behavior

The file/folders can be opened.

### To Reproduce

I install `yazi` using `cargo` as illustarted from installing page. 
All other dependences, including `file` (works normaly when test using `file -v`), is installed using `chocolatey`. 

### Configuration

No customized configuration. All default.

**Comment by sxyazi** [comment]
Please use the `file` that comes with Git for Windows, which we only recommend.

See docs here https://yazi-rs.github.io/docs/installation/#requirements

**Comment by RomaLzhih** [comment]
Great, it works, thanks!

**Comment by jeeeem** [comment]
> Please use the `file` that comes with Git for Windows, which we only recommend.
> 
> See docs here [yazi-rs.github.io/docs/installation/#requirements](https://yazi-rs.github.io/docs/installation/#requirements)

I have an inquiry regarding this, is there a way to use or separate only the file.exe so I don't have to include all of the other .exe files in git /usr/bin/ folder. Although atm, its working properly for me but at some point I may encounter an issue 'cos of the exe files that I have included in my path I do not know of. I actually tried to workaround this altho this is maybe a dumb moment, First, I separate the file.exe to try if it works, the `file.exe` works in terminal, then 2nd time, I created a bat file that is calling the git file.exe,but unfortunately those two does not work inside yazi when trying to edit specific file 'cos maybe there is obviously something going on that's why you recommended adding the path specifically with git usr/bin/ folder.

**Comment by sxyazi** [comment]
Hi @jeeeem, if you have Scoop installed, you can do this with the `scoop shim` command:

```
scoop shim add file PATH_TO_GIT_EXE_FILE
```

**Comment by jeeeem** [comment]
> Hi @jeeeem, if you have Scoop installed, you can do this with the `scoop shim` command:
> 
> ```
> scoop shim add file PATH_TO_GIT_FILE_EXE
> ```

Yup, this is what I wanted. Thanks for the tip. Didn't know I can do that in scoop. Maybe a good idea to add this on the docs.
