### ISSUE TITLE
ueberzug previews overlap and hide keymap menu

### ISSUE THREAD

**Issue by UtkarshVerma** [sxyazi/yazi#747]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

st

### Yazi version

yazi 0.2.3 (Arch Linux 2024-02-16) 

### Did you try the latest main branch to see if the problem got fixed?

Not tried, and I'll explain why below

### Describe the bug

`yazi` has a really helpful menu for showing keymaps, similar to `which-key` in nvim. If I use ueberzug previews, then the image is display on top of the menu, hiding the keymaps.

### Expected Behavior

Keymap menu is shown on top of the image.

### To Reproduce

1. Open a directory with images and let `yazi` preview a portrail image.
2. Try slowly pressing keys to trigger the keymap menu.

The menu will be hidden by the image.

**Comment by sxyazi** [comment]
Could you please record a GIF and let me see what happens?

**Comment by UtkarshVerma** [comment]
![2024-03-07_12-00](https://github.com/sxyazi/yazi/assets/31820255/c1bde2ca-31bc-45f6-9445-97fb9f0ac3d7)

Here's a screenshot.

**Comment by sxyazi** [comment]
This is how ueberzug works; it creates a new window that overlays the terminal window, so the terminal's content is covered because they are two separate windows.

It seems there's nothing Yazi can do here. If you want to avoid images covering content, use a terminal that natively supports any image protocol, such as kitty, sixel, or iTerm2.
