### ISSUE TITLE
Use starship prompt in header

### ISSUE THREAD

**Issue by knolljo** [sxyazi/yazi#767]
### Please describe the problem you're trying to solve

I'd like to have my starship prompt in the header instead of the default "~".
I've already experimented in lua with the header, because I found this [tip](https://yazi-rs.github.io/docs/tips#show-username-and-hostname-in-header).
As soon as I try to render it, the header just disappears entirely, am I doing something wrong?
 
In lf I configured the prompt like this:
```sh
cmd on-cd &{{
    export STARSHIP_SHELL=
    fmt="$(starship prompt)"
    lf -remote "send $id set promptfmt \"$fmt\""
}}
```
I'm sure something similar is possible in lua.
Thanks in advance!

### Would you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

Have the prompt of `starship prompt` appear in the header.
Maybe possible as a plugin or in init.lua.

**Comment by sxyazi** [comment]
After running `starship prompt`, I get this output:

```
❯ starship prompt

%{%}yazi%{%} on %{%} %{%}%{%}pr-c195b66a%{%} via %{%}🦀 %{%}%{%}v1.78.0-nightly%{%}%{%} %{%}
%{%}❯%{%} %
```

I'm not sure how to parse it, is there any documentation about it?

**Comment by knolljo** [comment]
Not really, I had the same issue in lf. My workaround was to set the env var
`STARSHIP_SHELL=` to nothing for the calling shell in lf. I think then the prompt just gets printed as ascii.

**Comment by sxyazi** [comment]
You can achieve it by overriding [`Header:cwd()`](https://github.com/sxyazi/yazi/blob/main/yazi-plugin/preset/components/header.lua) method.

The following code requires the latest main branch atm, since it uses a new `ui.Line.parse()` API to parse ANSI sequences into Yazi UI components.

https://github.com/sxyazi/yazi/assets/17523360/69b596b6-ab3d-4507-a02d-9c0cb7a90971


## Sync version

Save these lines as `~/.config/yazi/plugins/starship.yazi/init.lua`:

```lua
return {
  setup = function(st)
    Header.cwd = function()
      local cwd = cx.active.current.cwd
      if st.cwd ~= cwd then
        st.cwd, st.output = cwd, io.popen("STARSHIP_SHELL= starship prompt"):read("*a"):gsub("^%s+", "")
      end
      return ui.Line.parse(st.output)
    end
  end,
}
```

Then include it in your `~/.config/yazi/init.lua`:

```lua
require("starship"):setup()
```

## Async version (Recommend)

When in a very large Git repository, `starship` might slow down, thus blocking the Yazi UI thread rendering. However, this async version always executes `starship` asynchronously, avoiding any blocking on Yazi.

Save these lines as `~/.config/yazi/plugins/starship.yazi/init.lua`:

```lua
local save = ya.sync(function(st, cwd, output)
  if cx.active.current.cwd == Url(cwd) then
    st.output = output
    ya.render()
  end
end)

return {
  setup = function(st)
    Header.cwd = function()
      local cwd = cx.active.current.cwd
      if st.cwd ~= cwd then
        st.cwd = cwd
        ya.manager_emit("plugin", { st._name, args = ya.quote(tostring(cwd)) })
      end

      return ui.Line.parse(st.output or "")
    end
  end,

  entry = function(_, args)
    local output = Command("starship"):arg("prompt"):cwd(args[1]):env("STARSHIP_SHELL", ""):output()
    if output then
      save(args[1], output.stdout:gsub("^%s+", ""))
    end
  end,
}
```

Then include it in your `~/.config/yazi/init.lua`:

```lua
require("starship"):setup()
```

**Comment by knolljo** [comment]
Works as expected with main, thanks a lot! 
The async version is highly recommended, even on some mid-sized git repos there is a noticeable lag from starship.
Your last comment would probably fit very well into the tips section of your documentation, so that other users can find it easier :)
