### ISSUE TITLE
Show filename in prompt when deleting a file

### ISSUE THREAD

**Issue by cbr9** [sxyazi/yazi#827]
### Please describe the problem you're trying to solve

Hello, and thank you for creating yazi! Today I discovered it and ditched lf in favor of yazi :)

However, I have a request. I would like to see the name of the file I am about to delete, if it's just one, or even potentially a list of them if several are selected.

The point would be to avoid accidental deletions of important files

### Would you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

I'm not sure if delete_title can be a multiline string, or how that's rendered, but an idea would be to expose an extra variable, similar to lf's $fx or $fs. Then the prompt could be something like:

Delete the following files?
[...list of files]
(y/N)

**Comment by sxyazi** [comment]
The current deletion prompt is an input box, which cannot include multi-line file list information in the title. I plan to add a separate confirm component to achieve this, it looks like:

![CleanShot 2024-03-20 at 00 23 20](https://github.com/sxyazi/yazi/assets/17523360/d868eb59-fc4d-41f5-9e70-256c1627ba92)

"Are you sure you want to move this file to the trash?" can be replaced with multi-line text. (Screenshot from neo-tree, a file manager plugin in neovim)

But I haven't had enough time to complete it, would you like to give it a try? - If you're interested, I'll provide more details on how to implement it ;)

**Comment by cbr9** [comment]
Sure, if I get some free time I can play around with it for a bit

**Comment by thelamb** [comment]
This looked like a nice _good first issue_, so I decided to take a stab at it

I'm not familiar with Ratatui so it currently renders like this ;)
<img width="514" alt="afbeelding" src="https://github.com/sxyazi/yazi/assets/537058/19444b39-d99c-48f6-9803-9525cb7b0ded">

@sxyazi I'd appreciate feedback on the implementation so far. I think I only need to fix the rendering.
I will take some time to play with Ratatui since I hope to contribute more to yazi as a way to learn Rust.

I thought to start with just showing the targets as a Paragraph with the entries limited to a certain number. 

Better would be to show it as a scrollable list area: 
<img width="514" alt="afbeelding" src="https://github.com/sxyazi/yazi/assets/537058/3021bede-9a35-486d-96c1-5ab4568d05d3">
    
I'm not sure in this case if it's better to introduce a _DeleteConfirm_ widget or to make the _Confirm_ widget handle both general String messages and Lists

**Comment by sxyazi** [comment]
Excellent! I'm really happy to see that you're interested in this FR and willing to take it on. Thank you so much!

The code looks good overall, very clean. I think the remaining work is just some fine-tuning of the UI and I've sketched out a layout: 

![screenshot-000441](https://github.com/sxyazi/yazi/assets/17523360/259f2bec-3530-45dc-9a32-941876a69f52)

There's a prompt at the top, the middle is a list of files, and at the bottom there are two buttons for confirming or canceling.

**Comment by thelamb** [comment]
I'm glad it looks good overall! 

Last night I got the layout to this
<img width="514" alt="afbeelding" src="https://github.com/sxyazi/yazi/assets/537058/7bff2d4d-bf41-4f56-a93c-13642dc07753">

I'm considering whether to render the list of files as a List (like Select), or to use a Paragraph that is scrollable.
I'm leaning towards the Paragraph, and continue to have ConfirmCfg only store only _message: String_, and not a list of items. 

Then any function in ConfirmCfg, like the delete/trash is responsible for converting the input to a single String.

**Comment by sxyazi** [comment]
> I'm considering whether to render the list of files as a List (like Select), or to use a Paragraph that is scrollable.

We can store it internally as a [`ratatui::text::Text`](https://docs.rs/ratatui/latest/ratatui/text/struct.Text.html), i.e. `message: Text`, and render it as a scrollable [Paragraph](https://docs.rs/ratatui/latest/ratatui/widgets/struct.Paragraph.html). 

This will allow for greater flexibility so that it can be used elsewhere, like when we provide it as a Lua API similar to `ya.input()`.

**Comment by thelamb** [comment]
I'm happy with the layout so far:
![afbeelding](https://github.com/sxyazi/yazi/assets/537058/dccc1cba-5bbd-4acd-a447-c736d419d634)

Some things left to do:
  - Show scrollbar only if needed
  - Horizontal scrollbar, or line-wrap enough?
  - Mouse support for clicking buttons? 
  - Update help & plugin docs

I also added the lua binding following the ya.input logic (without the realtime), but I get an error in both ya.input(...) and ya.confirm(...) that I don't fully understand:

`2024-06-15T10:56:44.639667Z ERROR yazi::lives::lives: runtime error: attempt to yield from outside a coroutine
stack traceback:
        [C]: in ?
        [C]: in function 'coroutine.yield'
        [string "?"]:16: in field 'confirm'
        [string "yazi-plugin/src/loader/loader.rs:68:28"]:5: in function 'thelamb.entry'
    at yazi-fm/src/lives/lives.rs:68
`
My plugin code:
`return {
  entry = function(self, args)
    local value, event = ya.input({
      title = "Hello",
      position = { "top-center", y = 5, w = 70 },
    })

    -- local value, event = ya.confirm({
    --   title = "Hello",
    --   message = "Are you sure?",
    --   position = { "top-center", y = 5, w = 70, h = 30 },
    -- })
    ya.err("event: " + event)
    ya.err("value: " + value)
  end,
}`

The confirm binding implementation (but same error is in input())

![afbeelding](https://github.com/sxyazi/yazi/assets/537058/a4c20587-8c94-4363-92bc-c426ced03b0d)

I suppose it has something to do with the asyncness, since ya.notify works without any error. 

I'll continue to look into this but any pointer in the right direction is appreciated (I've pushed the latest code to my branch)

**Comment by thelamb** [comment]
Just a quick update: I'm happy with the current layout:

<img width="511" alt="afbeelding" src="https://github.com/sxyazi/yazi/assets/537058/61f822b9-de6f-4e9f-8e46-1059563dc850">

I'm still considering whether to introduce a horizontal scrollbar or if line-wrapping is sufficient. The vertical scrollbar is only shown if needed.
The last 'big' task would be to add mouse support for clicking the buttons. I only had a brief look at the mouse handling logic and wasn't sure how to do it because most seems to be handled in Lua. I'll continue to look into this once I wrap up the rest.

The lua binding is also working well (I did not find where I can update the [docs](https://yazi-rs.github.io/docs/plugins/utils) though)

Finally, I'm currently replacing the Input popup with Confirm in 2 other places:

- quit when there are ongoing tasks
- overwriting files

I'm struggling a bit with the 'quit' scenario. I like the solution of using select! to check whether the tasks are completing while the popup is shown. However, the Confirm popup no longer implements the 'realtime' logic of the Input. I'm trying to find a way for the logic to work with oneshot::Receiver but any pointers in the right direction would be appreciated (I updated my branch with the latest code)

<img width="991" alt="afbeelding" src="https://github.com/sxyazi/yazi/assets/537058/2e960cdf-e6fd-43ef-8973-b75b661c279f">

**Comment by sxyazi** [comment]
Thanks for the update!

> I'm still considering whether to introduce a horizontal scrollbar or if line-wrapping is sufficient
> The last 'big' task would be to add mouse support for clicking the buttons

We can not add it for now and leave it for future expansion

> I'll continue on this but I'd appreciate any suggestions to unblock this task

Could you submit it as a PR? I think I can get it fixed there quickly :)

**Comment by sxyazi** [comment]
Done by @thelamb in https://github.com/sxyazi/yazi/pull/1167, thanks! 🎉
