### ISSUE TITLE
Improve selection

### ISSUE THREAD

**Issue by freijon** [sxyazi/yazi#834]
### Please describe the problem you're trying to solve

I'm using tabs *a lot*. I think the solution in [xplr](https://xplr.dev) is really neat. Selection is global across all tabs & panes. You even have a selection view where you can see which files have been selected. The selected files are also available in an environment variable for convenience (e.g. for use in a shell). You can perform mass actions on these selections. I'd like to see something similar in `yazi`

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

1. Be able to select files globally (across tabs / folders) and use them with the already implemented $@, $1, $2, ...
By folders I mean you should be able to select files in the same tab, but in different locations (e.g. in /home and /tmp). In short: **Make selections global.**
3. "Cancel selection" should also work globally (but probably it would have to be something different than the default `Esc` key?)
4. Having a floating selection window (similar to the task window (`w` key)) could be useful to see what files you have selected over all contexts. In this window you could deselect individual files (or everything).
5. Put selected files in an environment variable for use with other tools
6. Having a "selection counter" (if >0) could be useful somewhere in the UI (top right?).
7. I see a synergy with https://github.com/sxyazi/yazi/issues/613 - We could use `fzf` to select multiple files which are not located in the same folder (e.g. launch `fzf` in the homedir and select all .png files located somewhere in the homedir)

**Comment by sxyazi** [comment]
I think global selection and multi-tab are two conflicting patterns - we have discussed it in https://github.com/sxyazi/yazi/issues/319 RFC.

I haven't used xplr, I'm curious how it manages to be compatible with both multiple tabs and global selection at the same time?

**Comment by freijon** [comment]
Well, they're not called tabs but "context". Instead of numeric tabs `xplr` just switches between a list of locations that you saved previously. I guess you can also think of them like temporary bookmarks to locations? And then there are also dual panes, you can have a left/right pane which can display two separate locations at the same time.

In either case `xplr` doesn't care what "context" (tab?) or pane is currently active, because selections are global.
Let's assume you select file `./A/file1.txt` in tab `1` and then in tab `2` you navigate from `./B` to `./A` --> `file1.txt` would already have a 'selected' indicator. When rendering the file list, you would have to check if something is in the selection list and show the green selected indicator.

I don't know the inner workings of `yazi`, but it seems like tabs work more like independent yazi sessions inside the same UI where selections / yank / cut are stored separately (locally).

**Comment by sxyazi** [comment]
Thank you for the explanation. 

I think "tabs" and "context" are different. In Yazi, file selection is a tab-specific temporary state, but there is a global "cut" and "copy" state. When users need to operate across tabs, they can switch the selection state to "cut" or "copy" state using the `x` or `y` key.

Unfortunately, I didn't come up with a good way to make Yazi support them both at the same time, and I quickly searched and found that xplr does [not support multi-tab](https://github.com/sayanarijit/xplr/issues/61#issuecomment-826604435), which may be because the author also realized that they are two opposite modes that conflict with each other.  

Perhaps in the future, we can explore the possibility of implementing it through the plugin system and it would be a state synchronization problem - let's say you have 3 tabs, if you select a file in the first tab, its selection state is synchronized to the other 2 tabs, achieving global selection through this workaround. I recently created a PR trying to provide plugin developers with the ability to synchronize this state, https://github.com/sxyazi/yazi/pull/826, if you are interested, feel free to track it.

Closing as not in the plan, sorry.
