### ISSUE TITLE
Jumping to a directy is giving and error

### ISSUE THREAD

**Issue by rxmmah** [sxyazi/yazi#857]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

foot

### Did you try the latest main branch to see if the problem got fixed?

Tried, but the problem still

### `yazi --debug` output

<details>

```sh
Yazi
    yazi 0.2.4 (Arch Linux 2024-03-10)

Environment
    OS: linux-x86_64 (unix)
    Debug: false

Emulator
    Emulator.via_env: ("foot", "tmux")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect: Foot

Adaptor
    Adaptor.matches: Sixel

tmux
    TMUX: true

Zellij
    ZELLIJ_SESSION_NAME: None

Desktop
    XDG_SESSION_TYPE: Some("wayland")
    WAYLAND_DISPLAY: Some("wayland-0")
    DISPLAY: Some(":0")

Ueberzug
    Version: Ok(Output { status: ExitStatus(unix_wait_status(0)), stdout: "ueberzugpp 2.9.4\n", stderr: "" })

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/kira/.local/state/yazi" directory.

```

</details>

### Describe the bug

when i navigate with yazi using the `yy` function, then press `z` to jump into a new directory and exit yazi, i get this error:
```
yy                                                                                                
invalid preview window option: down,30%,sharp
zoxide: fzf returned an error
cd:cd:1: no such file or directory: ^[[38;2;216;222;233m/home/kira/Music^[[0m
removed '/tmp/yazi-cwd.IDg9e'

```

### Expected Behavior

i excpect the PWD directory to be clean, not `^[[38;2;216;222;233m/home/kira/Music^[[0m`

### To Reproduce

launch yazi using yy function, move to a new dir then press z

**Comment by sxyazi** [comment]
Have you configured something like `alias cat=bat` in your shell? It looks like it's not the original `cat` command.

Please run `which cat`, `command -v cat`, `zoxide --version`, `fzf --version`, and paste their outputs here.

**Comment by rxmmah** [comment]
yes! i had `cat=bat` as alias.
now i am getting this ```
invalid preview window option: down,30%,sharp
zoxide: fzf returned an error

```
/usr/bin/cat
zoxide 0.9.4
0.23.1 (fc7630a)

**Comment by sxyazi** [comment]
This is because the `cat` command is used in Yazi's shell wrapper. Unfortunately, you have set it to `bat`, which is **different** from `cat`. `bat` includes ANSI color codes, which results in the garbled text you see. Removing this alias or modifying the shell wrapper to use the absolute path, i.e., `/usr/bin/cat` instead of `cat`, should resolve the issue. 

Regarding zoxide, the interactive mode relies on fzf. If fzf is not installed, the interactive mode of zoxide will not work. Please refer to the zoxide documentation at https://github.com/ajeetdsouza/zoxide?tab=readme-ov-file#installation
