### ISSUE TITLE
Sign commits and releases

### ISSUE THREAD

**Issue by faluta999** [sxyazi/yazi#862]
### Please describe the problem you're trying to solve

Please consider adding pgp signatures to your git commits and the releases.

These days, with state sponsored attacks targeting open source projects (see CVE-2024-3094), it would add a degree of confidence to ensure that:
1. Maintainer accounts are not compromised
2. Maintainers are part of the web of trust, thereby allowing established members of the open source community to verify key owner identities (while also allowing anonymity to most of the internet) 
3. Distribution maintainers have a reliable way to verify downloaded releases 

### Describe the solution you'd like

1. Encourage all contriburions to be signed and add signatures to the official releases.
2. Join the web of trust to add confidence in the key identities of official project maintainers.

**Comment by faluta999** [comment]
> From the first commit of Yazi, it already includes PGP signatures 👍🏻

That is an automated signature from the github key that is used when code is commited through githubs web UI.
It is by no means an effective signature and does not cover any of the use cases listed in this issue.
Anyone can commit code that is signed by this signature and displayed as verified.

To demonstrate: https://github.com/faluta999/yazi/commit/e4006ecf57aaa183cd35ff7efe802f6ff85d9976
(note the identical key id)

![a](https://github.com/sxyazi/yazi/assets/165730236/4162b3d4-4996-4478-8ee8-0f89ac02dc79)

Additionally the key does not have any identity besides the one from Github:
![b](https://github.com/sxyazi/yazi/assets/165730236/5d3b2922-5fa8-4152-8909-cd797e70454b)

Please reopen this issue and consider the problem seriously. This can all be addressed by a one time setup of pgp identities and everything else can be automated. If any advise about pgp and the web of trust is needed, I would be happy to help.

**Comment by sxyazi** [comment]
I think this is because that commit happens to be a merge of a PR - when you merge a PR in the GitHub Web UI, GitHub automatically generates a signature for it. If you want to see my own signature, you need to go to the [Commits page](https://github.com/sxyazi/yazi/pull/868/commits) of the PR, for example:

![CleanShot 2024-04-03 at 02 11 29](https://github.com/sxyazi/yazi/assets/17523360/10d34d43-c285-4371-805b-aa9b95c7c2a1)

And some commits are not merged from a PR but are directly committed to the main branch, in which case it will display my own PGP signature:

![CleanShot 2024-04-03 at 02 08 14](https://github.com/sxyazi/yazi/assets/17523360/28c3aa51-90bc-4cc5-b437-e5c7adf237fb)
