### ISSUE TITLE
Protection from copying a directory into itself

### ISSUE THREAD

**Issue by DanViTrinh** [sxyazi/yazi#894]
### Please describe the problem you're trying to solve

![240410_16h23m30s_screenshot](https://github.com/sxyazi/yazi/assets/80539964/342a06d1-8b1c-40b3-a34f-96782fa984ea)

cp has protection against copying a directory into itself. 

![240410_16h23m56s_screenshot](https://github.com/sxyazi/yazi/assets/80539964/096c876e-aa6f-4bc8-ab02-53afc31a4eed)

This is not present in yazi resulting in an operation running forever. 
Of course you could just quit yazi, so it is not an urgent feature, just a nice addition to yazi. 

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

A warning message when you are about to copy a directory into itself.

**Comment by sxyazi** [comment]
Hey, you can open the task manager by pressing the `w` key, then press `x` to cancel the failed task, keep the failed tasks in the task manager and display a red progress bar at the bottom to indicate to the user that it's an intentional design.

I don't think notifications are suitable for this scenario. For example, if a user copies 100 files and 30 of them fail, constantly popping up 30 notifications would be annoying. So I decided to just keep them in the task manager and use the red progress bar to quietly inform the user.

---

Regarding adding protection checks, it would be nice to have and this would make nested copying/moving more secure.

Anyone want to give it a try? I think `file_cut()` and `file_copy()` are the only two places that need to be changed:

https://github.com/sxyazi/yazi/blob/e7dc971416af2c59b0d1498579102318885642ca/yazi-scheduler/src/scheduler.rs#L70

https://github.com/sxyazi/yazi/blob/e7dc971416af2c59b0d1498579102318885642ca/yazi-scheduler/src/scheduler.rs#L102

**Comment by alexandruoprinca** [comment]
@sxyazi There is already some similar code preventing the file to be copied/cut onto itself: https://github.com/sxyazi/yazi/blob/e7dc971416af2c59b0d1498579102318885642ca/yazi-core/src/tasks/file.rs#L24
Shouldn't the protection check be added there as well, so in that case it doesn't even reach the scheduler?
Assuming you still want it to be in the scheduler, do you think that just checking and exiting earlier is enough?

**Comment by sxyazi** [comment]
Hey @alexandruoprinca, this is different. When the user moves/copies `A` to `A`, i.e., `A -> A`, Yazi assumes that the operation has been successful because nothing (and should not) change, so there is no need to give the user an error message.

However, the second image provided by OP is a process of `A -> A/A`, which leads to an infinite loop of `A -> A/A/A/...`.

**Comment by alexandruoprinca** [comment]
> Hey @alexandruoprinca, this is different. When the user moves/copies `A` to `A`, i.e., `A -> A`, Yazi assumes that the operation has been successful because nothing (and should not) change, so there is no need to give the user an error message.
> 
> However, the second image provided by OP is a process of `A -> A/A`, which leads to an infinite loop of `A -> A/A/A/...`.

Sorry for not being more explicit, i meant that there is already a particular place in the code where there is a check for 'A -> A', shouldn't the check for 'A -> A/A' be put there as well? So in the end in this if:
https://github.com/sxyazi/yazi/blob/e7dc971416af2c59b0d1498579102318885642ca/yazi-core/src/tasks/file.rs#L23
Another check can be added, something like:
`if force && *u == to && to.startsWith(*u) {
....`
