### ISSUE TITLE
built in mount menu

### ISSUE THREAD

**Issue by 4rtemis-4rrow** [sxyazi/yazi#927]
### Please describe the problem you're trying to solve

a way to easily manage drives

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

simply add a menu used to manage different drives/partitions (mount, unmount, CD to), would also be preferable if it showed all mounted partitions in an easily accessible path, though that depends on if yazi was designed from the start to be obscured from the file system or not

**Comment by sxyazi** [comment]
Hi, it's already included in the [Feature Request](https://github.com/sxyazi/yazi/issues/51#issuecomment-1757470132), but I want to implement it as a plugin, just like https://github.com/SL-RU/ranger_udisk_menu, instead of embedding it, because there are cross-platform issues - it only works for Unix users.

Ideally, built-in commands should satisfy all platforms, and implementing it as a plugin will provide greater flexibility, allowing users to configure them in Lua. If you or someone interested in implementing it, please let me know, and we can further explore it, closing as duplicate.

**Comment by 4rtemis-4rrow** [comment]
I mean, I can design great ncurses based UIs, and I could write the entire mounter myself, issue is, idk lua, so there's that

if we could write it in python, and then the init.lua just runs that, then yes, I could do it

**Comment by sxyazi** [comment]
Yup this is possible, by implementing it through Python and then using [`shell --block` command](https://yazi-rs.github.io/docs/configuration/keymap/#manager.shell) to call it as an external TUI program, just requires introducing Python as a separate dependency, the integration of `fzf` and `zoxide` is also achieved in this way - they are external TUI apps.

**Comment by 4rtemis-4rrow** [comment]
alright, great, I'll write it today, create a repo for it, and send you the link once it's done

would also be useful for people who want to use such a program, but don't want to use yazi, so there's that

**Comment by c02y** [comment]
There is a bash script called [bashmount](https://github.com/jamielinux/bashmount/), I used it in ranger or just in terminal, I tried it in yazi, it works but it doesn't display input.

**Comment by sxyazi** [comment]
Made a plugin for this, https://github.com/yazi-rs/plugins/tree/main/mount.yazi
