### ISSUE TITLE
Windows shortcut (`.lnk`) support

### ISSUE THREAD

**Issue by ThePython10110** [sxyazi/yazi#941]
### Please describe the problem you're trying to solve

At the moment, Yazi does not understand Windows shortcuts (`.lnk` files). They cannot be previewed, and you can't go inside shortcut folders.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Ideally, shortcuts should act basically the same as symlinks.

### Additional context

I don't know if this *really* counts as a feature request and not a bug report.

**Comment by sxyazi** [comment]
Hey, this is expected behavior.

In Windows, shortcuts and symlinks are different, Windows has a [specific concept for symlinks](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/mklink), which Yazi supports, but shortcuts are just regular files. 

Even if Yazi were to read and parse the contents of shortcuts, it wouldn't make sense because other command-line tools don't parse them.

For example, Yazi's essential dependency `file(1)`, when you run `file.exe -bL --mime-type "Visual Studio Code.lnk"`, you'll get:

```
application/x-ms-shortcut
```

instead of:

```
application/vnd.microsoft.portable-executable
```

I've specified `-L` when calling `file`, which means follow symlink, but because shortcuts and symlinks are *really* different, it's ineffective.

If you want to enter the directory pointed to by a shortcut, you can implement this as a Lua plugin. In the plugin, you would call an external command-line tool to resolve the shortcut path, and then call `ya.manager_emit("enter", { path })`, similar to what smart-enter does, https://yazi-rs.github.io/docs/tips#smart-enter
