### ISSUE TITLE
Segfaults on AMD FX series CPUs

### ISSUE THREAD

**Issue by yolorkit** [sxyazi/yazi#979]
### What system are you running Yazi on?

Linux X11, Ubuntu 22.04.4 LTS (GNU/Linux 6.5.0-28-generic x86_64)

### What terminal are you running Yazi in?

zsh / bash

### Did you try the latest code to see if this problem got fixed?

Tried, but the problem still

### `yazi --debug` output

<details>

```
target/debug/yazi --debug

Yazi
    Version: 0.2.5 (4c35f26 2024-04-30)
    OS: linux-x86_64 (unix)
    Debug: true

Emulator
    Emulator.via_env: ("xterm-256color", "")
    Emulator.via_csi: Ok(Konsole)
    Emulator.detect: Konsole

Adaptor
    Adaptor.matches: KittyOld

Desktop
    XDG_SESSION_TYPE: Some("tty")
    WAYLAND_DISPLAY: None
    DISPLAY: None

SSH
    shared.in_ssh_connection: true

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL: Some("/usr/bin/zsh")
    EDITOR: Some("nvim")
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE: None
    YAZI_CONFIG_HOME: None

file(1)
    Version: Ok(Output { status: ExitStatus(unix_wait_status(0)), stdout: "file-5.41\nmagic file from /etc/magic:/usr/share/misc/magic\n", stderr: "" })

Text Opener
    default: Some(Opener { run: "${EDITOR:=nvim} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block: Some(Opener { run: "${EDITOR:=nvim} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

tmux
    TMUX: false

Ueberzug++
    Version: Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })


```

</details>

### Describe the bug

Whenever i try to run yazi it segfaults

### Expected Behavior

Run as usual

### To Reproduce

I can reproduce it only on AMD FX series CPUs. Not sure what's the difference but so far out of all CPUs i've been using yazi with only those have a problem.

I have 2 machines with the exact same CPU and MB:
AMD FX(tm)-6300 Six-Core Processor
ASUSTeK  M5A78L-M/USB3

**Comment by sxyazi** [comment]
Thanks for the report!

If this is a CPU-specific issue, it will be a headache because I don't have that CPU... 

Can you help test it? First try building Yazi from the source code in debug mode (as per https://yazi-rs.github.io/docs/installation#build-from-source without the `--release` flag) and see what happens when you run it. Maybe we can find some clues from the more detailed error reports in debug mode.

**Comment by yolorkit** [comment]
[yazi.log](https://github.com/sxyazi/yazi/files/15162555/yazi.log)

I've run debug build. Updated first comment and uploaded this log file

**Comment by sxyazi** [comment]
If you run `yazi` instead of `yazi --debug` what will happen?

**Comment by yolorkit** [comment]
If i simply run yazi i get this:
`[1]    12746 segmentation fault (core dumped)  target/debug/yazi`

**Comment by sxyazi** [comment]
Please try the following steps:

1. Remove the Jemalloc memory allocator, then rebuild Yazi in debug mode to see what happens

   https://github.com/sxyazi/yazi/blob/bdb28f769137fd34ff162b7bd49f572ca375c0da/yazi-fm/src/main.rs#L4-L6

2. Comment out each line in the main function one by one to see if we can narrow down the issue to a specific line.

   https://github.com/sxyazi/yazi/blob/bdb28f769137fd34ff162b7bd49f572ca375c0da/yazi-fm/src/main.rs#L36-L60

**Comment by yolorkit** [comment]
I've comment out Jemalloc and this was enough to make it work. Now i need to enable it and comment out other lines that you provided. Did i understand it right?

**Comment by yolorkit** [comment]
That's right. No segfaults so far.

**Comment by sxyazi** [comment]
I tried to write a [conditional compilation](https://doc.rust-lang.org/reference/conditional-compilation.html) instruction for AMD CPUs, but I found that cargo does not support detecting the type of CPU at compile time. 

Perhaps the only solution for now is to manually comment out the Jemalloc memory allocator and build it from source. 

This issue is quite weird; so far, I haven't received any similar reports, and I couldn't find any related bug reports in the Jemalloc repository. I'm not even sure if this is specific to AMD CPUs...

**Comment by yolorkit** [comment]
Ok, i'll just comment it out from now on.

Out of curiosity i've tried to enable Jemmaloc and comment out line by line to see what happens. It segfaulted as usual up until this:
```
 //  _ = fdlimit::raise_fd_limit();
  
 //  yazi_shared::init();
  
 //  yazi_config::init()?;
```

Then it printed some errors in the attached file.

[yazi-debug-run.log](https://github.com/sxyazi/yazi/files/15164113/yazi-debug-run.log)

**Comment by sxyazi** [comment]
This is an unrelated error, it occurred at 

https://github.com/sxyazi/yazi/blob/bdb28f769137fd34ff162b7bd49f572ca375c0da/yazi-plugin/src/config.rs#L21

The reason is that the `yazi-plugin` crate is accessing the `MANAGER` variable in the `yazi-config` crate, and because you commented out `yazi_config::init()`, the variable (`MANAGER`) was not initialized.

**Comment by sxyazi** [comment]
If you want to test it further, I suggest commenting out from the back to the front, because the later code relies on the initialization work of the earlier code.

**Comment by yolorkit** [comment]
Mostly the same segfaults, one newer error and one similar to the previous. I've added both in files.

[y_1.log](https://github.com/sxyazi/yazi/files/15165458/y_1.log)
[y_2.log](https://github.com/sxyazi/yazi/files/15165459/y_2.log)

**Comment by sxyazi** [comment]
It looks like still has the same error, the second one is because you commented `yazi_dds::init()` out but the following `yazi_dds::serve()` relies on it.

**Comment by sxyazi** [comment]
Closing this issue with [a workaround](https://github.com/sxyazi/yazi/issues/979#issuecomment-2085217950). If you find more clues leading to it, please continue to reply to this issue or create a new one.
