### ISSUE TITLE
change the behavior of paste to prompt user instead of renaming pasted files

### ISSUE THREAD

**Issue by teto** [sxyazi/yazi#982]
### Please describe the problem you're trying to solve

I copy/pasted multiples files via `y` / `p`  in a folder that contained files with the same filename (actually it was an earlier partial copy/paste). 

I was expecting for yazi to override the filenames but instead it renamed the pasted files and suffixed them with `_1` if I remember correctly.
I looked if I could achieve that with the current config and I can with https://yazi-rs.github.io/docs/configuration/keymap#manager.paste --force

Having this as a default can be tricky though. You might override a file without realizing it. Same for the current behavior, you might think you overrode the file but instead yazi pasted a renamed file.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

I think a better default would be to prompt the user wether to overwrite existing file (maybe on a per-overwrite basis), akin to `paste --conflict=prompt`  (`--force` could become `--conflict=prompt`)

**Comment by teto** [comment]
Could be a single prompt "Override **_all files_** (y/n)" then ? the current default behavior created lots of file I didn't want to be created and I had then to clean them up manually.

**Comment by sxyazi** [comment]
I didn't quite understand what you meant. Are you saying that when encountering the first conflicting file, a confirmation prompt will appear, and if the user confirms, all conflicting items will be overwritten, otherwise they will all be appended with "_"? 

If so, there is still a possibility of accidental activation because this confirmation prompt may appear at an unexpected time for the user. It is different from a deletion confirmation, which occurs **after** the user action and **before** progress begins, while the copy confirmation can occur at any time **after** the progress begins, because the entire process is async for the user.

**Comment by sxyazi** [comment]
Closing as not in the plan
