### ISSUE TITLE
ya.notify title and content ignore tab character (`\t')

### ISSUE THREAD

**Issue by SolitudeSF** [sxyazi/yazi#996]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

kitty

### Describe the bug

tab character is completely skipped

### Expected Behavior

tab character produces at least one whitespace

### To Reproduce

`ya.notify {  title = "a\tb", content ="a\tb", timeout = 5 }`

**Comment by sxyazi** [comment]
This is expected behavior because the width of `\t` is variable, so it's not clear what its specific width is, and `unicode-width` currently [recognizes it as 0](https://github.com/ratatui-org/ratatui/issues/876#issuecomment-1913356310).

I suggest manually replacing `\t` with spaces, just as Yazi does elsewhere:

https://github.com/sxyazi/yazi/blob/36b3ffafc1a2e227959b742002d4ff60aa31df16/yazi-plugin/preset/plugins/json.lua#L39
